
package it.eng.auriga.repository2.webservices.getattoperacquisti;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSGetAttoPerAcquistiService", targetNamespace = "http://getattoperacquisti.webservices.repository2.auriga.eng.it", wsdlLocation = "/wsdl/WSGetAttoPerAcquisti.wsdl")
public class WSGetAttoPerAcquistiService
    extends Service
{

    private final static URL WSGETATTOPERACQUISTISERVICE_WSDL_LOCATION;
    private final static WebServiceException WSGETATTOPERACQUISTISERVICE_EXCEPTION;
    private final static QName WSGETATTOPERACQUISTISERVICE_QNAME = new QName("http://getattoperacquisti.webservices.repository2.auriga.eng.it", "WSGetAttoPerAcquistiService");

    static {
        WSGETATTOPERACQUISTISERVICE_WSDL_LOCATION = it.eng.auriga.repository2.webservices.getattoperacquisti.WSGetAttoPerAcquistiService.class.getResource("/wsdl/WSGetAttoPerAcquisti.wsdl");
        WebServiceException e = null;
        if (WSGETATTOPERACQUISTISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/WSGetAttoPerAcquisti.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSGETATTOPERACQUISTISERVICE_EXCEPTION = e;
    }

    public WSGetAttoPerAcquistiService() {
        super(__getWsdlLocation(), WSGETATTOPERACQUISTISERVICE_QNAME);
    }

    public WSGetAttoPerAcquistiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSGETATTOPERACQUISTISERVICE_QNAME, features);
    }

    public WSGetAttoPerAcquistiService(URL wsdlLocation) {
        super(wsdlLocation, WSGETATTOPERACQUISTISERVICE_QNAME);
    }

    public WSGetAttoPerAcquistiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSGETATTOPERACQUISTISERVICE_QNAME, features);
    }

    public WSGetAttoPerAcquistiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGetAttoPerAcquistiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSIGetAttoPerAcquisti
     */
    @WebEndpoint(name = "WSGetAttoPerAcquistiPort")
    public WSIGetAttoPerAcquisti getWSGetAttoPerAcquistiPort() {
        return super.getPort(new QName("http://getattoperacquisti.webservices.repository2.auriga.eng.it", "WSGetAttoPerAcquistiPort"), WSIGetAttoPerAcquisti.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns WSIGetAttoPerAcquisti
     */
    @WebEndpoint(name = "WSGetAttoPerAcquistiPort")
    public WSIGetAttoPerAcquisti getWSGetAttoPerAcquistiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://getattoperacquisti.webservices.repository2.auriga.eng.it", "WSGetAttoPerAcquistiPort"), WSIGetAttoPerAcquisti.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSGETATTOPERACQUISTISERVICE_EXCEPTION!= null) {
            throw WSGETATTOPERACQUISTISERVICE_EXCEPTION;
        }
        return WSGETATTOPERACQUISTISERVICE_WSDL_LOCATION;
    }

}
