/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.subjectregistryservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubjectRegistryService", targetNamespace = "subjectregistryservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/subregistryWS.wsdl")
public class SubjectRegistryService
    extends Service
{

    private final static URL SUBJECTREGISTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBJECTREGISTRYSERVICE_EXCEPTION;
    private final static QName SUBJECTREGISTRYSERVICE_QNAME = new QName("subjectregistryservice.acaris.acta.doqui.it", "SubjectRegistryService");

    static {
        SUBJECTREGISTRYSERVICE_WSDL_LOCATION = it.doqui.acta.acaris.subjectregistryservice.SubjectRegistryService.class.getResource("/wsdl/subregistryWS.wsdl");
        WebServiceException e = null;
        if (SUBJECTREGISTRYSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/subregistryWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SUBJECTREGISTRYSERVICE_EXCEPTION = e;
    }

    public SubjectRegistryService() {
        super(__getWsdlLocation(), SUBJECTREGISTRYSERVICE_QNAME);
    }

    public SubjectRegistryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBJECTREGISTRYSERVICE_QNAME, features);
    }

    public SubjectRegistryService(URL wsdlLocation) {
        super(wsdlLocation, SUBJECTREGISTRYSERVICE_QNAME);
    }

    public SubjectRegistryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBJECTREGISTRYSERVICE_QNAME, features);
    }

    public SubjectRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubjectRegistryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubjectRegistryServicePort
     */
    @WebEndpoint(name = "SubjectRegistryServicePort")
    public SubjectRegistryServicePort getSubjectRegistryServicePort() {
        return super.getPort(new QName("subjectregistryservice.acaris.acta.doqui.it", "SubjectRegistryServicePort"), SubjectRegistryServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns SubjectRegistryServicePort
     */
    @WebEndpoint(name = "SubjectRegistryServicePort")
    public SubjectRegistryServicePort getSubjectRegistryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("subjectregistryservice.acaris.acta.doqui.it", "SubjectRegistryServicePort"), SubjectRegistryServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBJECTREGISTRYSERVICE_EXCEPTION!= null) {
            throw SUBJECTREGISTRYSERVICE_EXCEPTION;
        }
        return SUBJECTREGISTRYSERVICE_WSDL_LOCATION;
    }

}
