/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.officialbookservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.doqui.acta.acaris.common.GetPropertiesMassive;
import it.doqui.acta.acaris.common.GetPropertiesMassiveResponse;
import it.doqui.acta.acaris.common.Query;
import it.doqui.acta.acaris.common.QueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OfficialBookServicePort", targetNamespace = "officialbookservice.acaris.acta.doqui.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.doqui.acta.acaris.common.ObjectFactory.class,
    it.doqui.acta.acaris.officialbookservice.ObjectFactory.class,
    it.doqui.acta.acaris.common.prt.ObjectFactory.class
})
public interface OfficialBookServicePort {


    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.CreaRegistrazioneResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "creaRegistrazioneResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public CreaRegistrazioneResponse creaRegistrazione(
        @WebParam(name = "creaRegistrazione", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        CreaRegistrazione input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.ImportaRegistrazioneResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "importaRegistrazioneResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public ImportaRegistrazioneResponse importaRegistrazione(
        @WebParam(name = "importaRegistrazione", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        ImportaRegistrazione input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.GetRegistriesResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getRegistriesResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public GetRegistriesResponse getRegistries(
        @WebParam(name = "getRegistries", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        GetRegistries input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.GetPropertiesResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesResponse getProperties(
        @WebParam(name = "getProperties", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        GetProperties input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.UpdatePropertiesResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "updatePropertiesResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public UpdatePropertiesResponse updateProperties(
        @WebParam(name = "updateProperties", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        UpdateProperties input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.QueryResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "queryResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public QueryResponse query(
        @WebParam(name = "query", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        Query input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.GetPropertiesMassiveResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesMassiveResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesMassiveResponse getPropertiesMassive(
        @WebParam(name = "getPropertiesMassive", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        GetPropertiesMassive input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.CreaAnnotazioneOBResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "creaAnnotazioneOBResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public CreaAnnotazioneOBResponse creaAnnotazioneOB(
        @WebParam(name = "creaAnnotazioneOB", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        CreaAnnotazioneOB input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.InviaSegnaturaResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "inviaSegnaturaResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public InviaSegnaturaResponse inviaSegnatura(
        @WebParam(name = "inviaSegnatura", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        InviaSegnatura input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.InviaSegnaturaRegistrazioneResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "inviaSegnaturaRegistrazioneResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public InviaSegnaturaRegistrazioneResponse inviaSegnaturaRegistrazione(
        @WebParam(name = "inviaSegnaturaRegistrazione", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        InviaSegnaturaRegistrazione input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.RicercaDatiInterscambioResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "ricercaDatiInterscambioResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public RicercaDatiInterscambioResponse ricercaDatiInterscambio(
        @WebParam(name = "ricercaDatiInterscambio", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        RicercaDatiInterscambio input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.officialbookservice.AnnullaRegistrazioneResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "annullaRegistrazioneResponse", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "output")
    public AnnullaRegistrazioneResponse annullaRegistrazione(
        @WebParam(name = "annullaRegistrazione", targetNamespace = "officialbookservice.acaris.acta.doqui.it", partName = "input")
        AnnullaRegistrazione input)
        throws AcarisException
    ;

}
