/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.backofficeservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.doqui.acta.acaris.backoffice.GetDescendants;
import it.doqui.acta.acaris.backoffice.GetDescendantsResponse;
import it.doqui.acta.acaris.backoffice.GetDettaglioAOO;
import it.doqui.acta.acaris.backoffice.GetDettaglioAOOResponse;
import it.doqui.acta.acaris.backoffice.GetDettaglioStruttura;
import it.doqui.acta.acaris.backoffice.GetDettaglioStrutturaResponse;
import it.doqui.acta.acaris.backoffice.GetObjectParents;
import it.doqui.acta.acaris.backoffice.GetObjectParentsResponse;
import it.doqui.acta.acaris.backoffice.GetPrincipal;
import it.doqui.acta.acaris.backoffice.GetPrincipalExt;
import it.doqui.acta.acaris.backoffice.GetPrincipalExtResponse;
import it.doqui.acta.acaris.backoffice.GetPrincipalResponse;
import it.doqui.acta.acaris.backoffice.GetProperties;
import it.doqui.acta.acaris.backoffice.GetPropertiesResponse;
import it.doqui.acta.acaris.backoffice.GetQueryableObjectMetadata;
import it.doqui.acta.acaris.backoffice.GetQueryableObjectMetadataResponse;
import it.doqui.acta.acaris.backoffice.GetQueryableObjects;
import it.doqui.acta.acaris.backoffice.GetQueryableObjectsResponse;
import it.doqui.acta.acaris.backoffice.GetRelazioniStruttura;
import it.doqui.acta.acaris.backoffice.GetRelazioniStrutturaResponse;
import it.doqui.acta.acaris.common.GetPropertiesMassive;
import it.doqui.acta.acaris.common.GetPropertiesMassiveResponse;
import it.doqui.acta.acaris.common.Query;
import it.doqui.acta.acaris.common.QueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackOfficeServicePort", targetNamespace = "backofficeservice.acaris.acta.doqui.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.doqui.acta.acaris.backoffice.ObjectFactory.class,
    it.doqui.acta.acaris.common.ObjectFactory.class
})
public interface BackOfficeServicePort {


    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetPrincipalResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPrincipalResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetPrincipalResponse getPrincipal(
        @WebParam(name = "getPrincipal", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetPrincipal input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetPrincipalExtResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPrincipalExtResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetPrincipalExtResponse getPrincipalExt(
        @WebParam(name = "getPrincipalExt", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetPrincipalExt input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetDescendantsResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getDescendantsResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetDescendantsResponse getDescendants(
        @WebParam(name = "getDescendants", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetDescendants input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetObjectParentsResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getObjectParentsResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetObjectParentsResponse getObjectParents(
        @WebParam(name = "getObjectParents", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetObjectParents input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetRelazioniStrutturaResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getRelazioniStrutturaResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetRelazioniStrutturaResponse getRelazioniStruttura(
        @WebParam(name = "getRelazioniStruttura", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetRelazioniStruttura input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetPropertiesResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesResponse getProperties(
        @WebParam(name = "getProperties", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetProperties input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.GetPropertiesMassiveResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesMassiveResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesMassiveResponse getPropertiesMassive(
        @WebParam(name = "getPropertiesMassive", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        GetPropertiesMassive input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetDettaglioAOOResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getDettaglioAOOResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetDettaglioAOOResponse getDettaglioAOO(
        @WebParam(name = "getDettaglioAOO", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetDettaglioAOO input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetDettaglioStrutturaResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getDettaglioStrutturaResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetDettaglioStrutturaResponse getDettaglioStruttura(
        @WebParam(name = "getDettaglioStruttura", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetDettaglioStruttura input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetQueryableObjectsResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getQueryableObjectsResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetQueryableObjectsResponse getQueryableObjects(
        @WebParam(name = "getQueryableObjects", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetQueryableObjects input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.backoffice.GetQueryableObjectMetadataResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getQueryableObjectMetadataResponse", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "output")
    public GetQueryableObjectMetadataResponse getQueryableObjectMetadata(
        @WebParam(name = "getQueryableObjectMetadata", targetNamespace = "backoffice.acaris.acta.doqui.it", partName = "input")
        GetQueryableObjectMetadata input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.QueryResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "queryResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public QueryResponse query(
        @WebParam(name = "query", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        Query input)
        throws AcarisException
    ;

}
