/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.backofficeservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BackOfficeService", targetNamespace = "backofficeservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/backofficeWS.wsdl")
public class BackOfficeService
    extends Service
{

    private final static URL BACKOFFICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BACKOFFICESERVICE_EXCEPTION;
    private final static QName BACKOFFICESERVICE_QNAME = new QName("backofficeservice.acaris.acta.doqui.it", "BackOfficeService");

    static {
        BACKOFFICESERVICE_WSDL_LOCATION = it.doqui.acta.acaris.backofficeservice.BackOfficeService.class.getResource("/wsdl/backofficeWS.wsdl");
        WebServiceException e = null;
        if (BACKOFFICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/backofficeWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BACKOFFICESERVICE_EXCEPTION = e;
    }

    public BackOfficeService() {
        super(__getWsdlLocation(), BACKOFFICESERVICE_QNAME);
    }

    public BackOfficeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BACKOFFICESERVICE_QNAME, features);
    }

    public BackOfficeService(URL wsdlLocation) {
        super(wsdlLocation, BACKOFFICESERVICE_QNAME);
    }

    public BackOfficeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BACKOFFICESERVICE_QNAME, features);
    }

    public BackOfficeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackOfficeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BackOfficeServicePort
     */
    @WebEndpoint(name = "BackOfficeServicePort")
    public BackOfficeServicePort getBackOfficeServicePort() {
        return super.getPort(new QName("backofficeservice.acaris.acta.doqui.it", "BackOfficeServicePort"), BackOfficeServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns BackOfficeServicePort
     */
    @WebEndpoint(name = "BackOfficeServicePort")
    public BackOfficeServicePort getBackOfficeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("backofficeservice.acaris.acta.doqui.it", "BackOfficeServicePort"), BackOfficeServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BACKOFFICESERVICE_EXCEPTION!= null) {
            throw BACKOFFICESERVICE_EXCEPTION;
        }
        return BACKOFFICESERVICE_WSDL_LOCATION;
    }

}
