
package it.eng.auriga.repository2.webservices.trovadocfolder;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSTrovaDocFolderService", targetNamespace = "http://trovadocfolder.webservices.repository2.auriga.eng.it", wsdlLocation = "/wsdl/WSTrovaDocFolder.wsdl")
public class WSTrovaDocFolderService
    extends Service
{

    private final static URL WSTROVADOCFOLDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTROVADOCFOLDERSERVICE_EXCEPTION;
    private final static QName WSTROVADOCFOLDERSERVICE_QNAME = new QName("http://trovadocfolder.webservices.repository2.auriga.eng.it", "WSTrovaDocFolderService");

    static {
        WSTROVADOCFOLDERSERVICE_WSDL_LOCATION = it.eng.auriga.repository2.webservices.trovadocfolder.WSTrovaDocFolderService.class.getResource("/wsdl/WSTrovaDocFolder.wsdl");
        WebServiceException e = null;
        if (WSTROVADOCFOLDERSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/WSTrovaDocFolder.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSTROVADOCFOLDERSERVICE_EXCEPTION = e;
    }

    public WSTrovaDocFolderService() {
        super(__getWsdlLocation(), WSTROVADOCFOLDERSERVICE_QNAME);
    }

    public WSTrovaDocFolderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTROVADOCFOLDERSERVICE_QNAME, features);
    }

    public WSTrovaDocFolderService(URL wsdlLocation) {
        super(wsdlLocation, WSTROVADOCFOLDERSERVICE_QNAME);
    }

    public WSTrovaDocFolderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTROVADOCFOLDERSERVICE_QNAME, features);
    }

    public WSTrovaDocFolderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTrovaDocFolderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSITrovaDocFolder
     */
    @WebEndpoint(name = "WSTrovaDocFolderPort")
    public WSITrovaDocFolder getWSTrovaDocFolderPort() {
        return super.getPort(new QName("http://trovadocfolder.webservices.repository2.auriga.eng.it", "WSTrovaDocFolderPort"), WSITrovaDocFolder.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns WSITrovaDocFolder
     */
    @WebEndpoint(name = "WSTrovaDocFolderPort")
    public WSITrovaDocFolder getWSTrovaDocFolderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://trovadocfolder.webservices.repository2.auriga.eng.it", "WSTrovaDocFolderPort"), WSITrovaDocFolder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTROVADOCFOLDERSERVICE_EXCEPTION!= null) {
            throw WSTROVADOCFOLDERSERVICE_EXCEPTION;
        }
        return WSTROVADOCFOLDERSERVICE_WSDL_LOCATION;
    }

}
