/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.multifilingservice;

import javax.xml.ws.WebFault;

import it.doqui.acta.acaris.common.AcarisFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "acarisFault", targetNamespace = "common.acaris.acta.doqui.it")
public class AcarisException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AcarisFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AcarisException(String message, AcarisFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AcarisException(String message, AcarisFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.doqui.acta.acaris.common.AcarisFaultType
     */
    public AcarisFaultType getFaultInfo() {
        return faultInfo;
    }

}
