/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.multifilingservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MultifilingService", targetNamespace = "multifilingservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/multifillingWS.wsdl")
public class MultifilingService
    extends Service
{

    private final static URL MULTIFILINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException MULTIFILINGSERVICE_EXCEPTION;
    private final static QName MULTIFILINGSERVICE_QNAME = new QName("multifilingservice.acaris.acta.doqui.it", "MultifilingService");

    static {
        MULTIFILINGSERVICE_WSDL_LOCATION = it.doqui.acta.acaris.multifilingservice.MultifilingService.class.getResource("/wsdl/multifillingWS.wsdl");
        WebServiceException e = null;
        if (MULTIFILINGSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/multifillingWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MULTIFILINGSERVICE_EXCEPTION = e;
    }

    public MultifilingService() {
        super(__getWsdlLocation(), MULTIFILINGSERVICE_QNAME);
    }

    public MultifilingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTIFILINGSERVICE_QNAME, features);
    }

    public MultifilingService(URL wsdlLocation) {
        super(wsdlLocation, MULTIFILINGSERVICE_QNAME);
    }

    public MultifilingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTIFILINGSERVICE_QNAME, features);
    }

    public MultifilingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultifilingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MultifilingServicePort
     */
    @WebEndpoint(name = "MultifilingServicePort")
    public MultifilingServicePort getMultifilingServicePort() {
        return super.getPort(new QName("multifilingservice.acaris.acta.doqui.it", "MultifilingServicePort"), MultifilingServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns MultifilingServicePort
     */
    @WebEndpoint(name = "MultifilingServicePort")
    public MultifilingServicePort getMultifilingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("multifilingservice.acaris.acta.doqui.it", "MultifilingServicePort"), MultifilingServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTIFILINGSERVICE_EXCEPTION!= null) {
            throw MULTIFILINGSERVICE_EXCEPTION;
        }
        return MULTIFILINGSERVICE_WSDL_LOCATION;
    }

}
