/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.managementservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManagementService", targetNamespace = "managementservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/managementWS.wsdl")
public class ManagementService
    extends Service
{

    private final static URL MANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGEMENTSERVICE_EXCEPTION;
    private final static QName MANAGEMENTSERVICE_QNAME = new QName("managementservice.acaris.acta.doqui.it", "ManagementService");

    static {
        MANAGEMENTSERVICE_WSDL_LOCATION = it.doqui.acta.acaris.managementservice.ManagementService.class.getResource("/wsdl/managementWS.wsdl");
        WebServiceException e = null;
        if (MANAGEMENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/managementWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MANAGEMENTSERVICE_EXCEPTION = e;
    }

    public ManagementService() {
        super(__getWsdlLocation(), MANAGEMENTSERVICE_QNAME);
    }

    public ManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGEMENTSERVICE_QNAME, features);
    }

    public ManagementService(URL wsdlLocation) {
        super(wsdlLocation, MANAGEMENTSERVICE_QNAME);
    }

    public ManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGEMENTSERVICE_QNAME, features);
    }

    public ManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManagementServicePort
     */
    @WebEndpoint(name = "ManagementServicePort")
    public ManagementServicePort getManagementServicePort() {
        return super.getPort(new QName("managementservice.acaris.acta.doqui.it", "ManagementServicePort"), ManagementServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ManagementServicePort
     */
    @WebEndpoint(name = "ManagementServicePort")
    public ManagementServicePort getManagementServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("managementservice.acaris.acta.doqui.it", "ManagementServicePort"), ManagementServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGEMENTSERVICE_EXCEPTION!= null) {
            throw MANAGEMENTSERVICE_EXCEPTION;
        }
        return MANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
