/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.managementservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.doqui.acta.acaris.management.AddAnnotazioni;
import it.doqui.acta.acaris.management.AddAnnotazioniResponse;
import it.doqui.acta.acaris.management.GetVitalRecordCode;
import it.doqui.acta.acaris.management.GetVitalRecordCodeResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManagementServicePort", targetNamespace = "managementservice.acaris.acta.doqui.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.doqui.acta.acaris.common.ObjectFactory.class,
    it.doqui.acta.acaris.management.ObjectFactory.class
})
public interface ManagementServicePort {


    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.management.GetVitalRecordCodeResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getVitalRecordCodeResponse", targetNamespace = "management.acaris.acta.doqui.it", partName = "output")
    public GetVitalRecordCodeResponse getVitalRecordCode(
        @WebParam(name = "getVitalRecordCode", targetNamespace = "management.acaris.acta.doqui.it", partName = "input")
        GetVitalRecordCode input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.management.AddAnnotazioniResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "addAnnotazioniResponse", targetNamespace = "management.acaris.acta.doqui.it", partName = "output")
    public AddAnnotazioniResponse addAnnotazioni(
        @WebParam(name = "addAnnotazioni", targetNamespace = "management.acaris.acta.doqui.it", partName = "input")
        AddAnnotazioni input)
        throws AcarisException
    ;

}
