/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.documentservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentService", targetNamespace = "documentservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/documentWS.wsdl")
public class DocumentService
    extends Service
{

    private final static URL DOCUMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTSERVICE_EXCEPTION;
    private final static QName DOCUMENTSERVICE_QNAME = new QName("documentservice.acaris.acta.doqui.it", "DocumentService");

    static {
        DOCUMENTSERVICE_WSDL_LOCATION = it.doqui.acta.acaris.documentservice.DocumentService.class.getResource("/wsdl/documentWS.wsdl");
        WebServiceException e = null;
        if (DOCUMENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/documentWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DOCUMENTSERVICE_EXCEPTION = e;
    }

    public DocumentService() {
        super(__getWsdlLocation(), DOCUMENTSERVICE_QNAME);
    }

    public DocumentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTSERVICE_QNAME, features);
    }

    public DocumentService(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTSERVICE_QNAME);
    }

    public DocumentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTSERVICE_QNAME, features);
    }

    public DocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentServicePort
     */
    @WebEndpoint(name = "DocumentServicePort")
    public DocumentServicePort getDocumentServicePort() {
        return super.getPort(new QName("documentservice.acaris.acta.doqui.it", "DocumentServicePort"), DocumentServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns DocumentServicePort
     */
    @WebEndpoint(name = "DocumentServicePort")
    public DocumentServicePort getDocumentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("documentservice.acaris.acta.doqui.it", "DocumentServicePort"), DocumentServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTSERVICE_EXCEPTION!= null) {
            throw DOCUMENTSERVICE_EXCEPTION;
        }
        return DOCUMENTSERVICE_WSDL_LOCATION;
    }

}
