/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.documentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.doqui.acta.acaris.common.GetPropertiesMassive;
import it.doqui.acta.acaris.common.GetPropertiesMassiveResponse;
import it.doqui.acta.acaris.document.CreaDocumento;
import it.doqui.acta.acaris.document.CreaDocumentoFisicoInDocumentRoot;
import it.doqui.acta.acaris.document.CreaDocumentoFisicoInDocumentRootResponse;
import it.doqui.acta.acaris.document.CreaDocumentoResponse;
import it.doqui.acta.acaris.document.GetRappresentazioneDocumento;
import it.doqui.acta.acaris.document.GetRappresentazioneDocumentoResponse;
import it.doqui.acta.acaris.document.TrasformaDocumentoPlaceholderInDocumentoElettronico;
import it.doqui.acta.acaris.document.TrasformaDocumentoPlaceholderInDocumentoElettronicoResponse;
import it.doqui.acta.acaris.document.UploadContenutoFisico;
import it.doqui.acta.acaris.document.UploadContenutoFisicoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentServicePort", targetNamespace = "documentservice.acaris.acta.doqui.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.doqui.acta.acaris.archive.ObjectFactory.class,
    it.doqui.acta.acaris.common.ObjectFactory.class,
    it.doqui.acta.acaris.document.ObjectFactory.class,
    it.doqui.acta.acaris.documentservice.ObjectFactory.class
})
public interface DocumentServicePort {


    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.document.CreaDocumentoResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "creaDocumentoResponse", targetNamespace = "document.acaris.acta.doqui.it", partName = "output")
    public CreaDocumentoResponse creaDocumento(
        @WebParam(name = "creaDocumento", targetNamespace = "document.acaris.acta.doqui.it", partName = "input")
        CreaDocumento input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.document.GetRappresentazioneDocumentoResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getRappresentazioneDocumentoResponse", targetNamespace = "document.acaris.acta.doqui.it", partName = "output")
    public GetRappresentazioneDocumentoResponse getRappresentazioneDocumento(
        @WebParam(name = "getRappresentazioneDocumento", targetNamespace = "document.acaris.acta.doqui.it", partName = "input")
        GetRappresentazioneDocumento input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.document.TrasformaDocumentoPlaceholderInDocumentoElettronicoResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "trasformaDocumentoPlaceholderInDocumentoElettronicoResponse", targetNamespace = "document.acaris.acta.doqui.it", partName = "output")
    public TrasformaDocumentoPlaceholderInDocumentoElettronicoResponse trasformaDocumentoPlaceholderInDocumentoElettronico(
        @WebParam(name = "trasformaDocumentoPlaceholderInDocumentoElettronico", targetNamespace = "document.acaris.acta.doqui.it", partName = "input")
        TrasformaDocumentoPlaceholderInDocumentoElettronico input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.GetPropertiesMassiveResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesMassiveResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesMassiveResponse getPropertiesMassive(
        @WebParam(name = "getPropertiesMassive", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        GetPropertiesMassive input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.document.CreaDocumentoFisicoInDocumentRootResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "creaDocumentoFisicoInDocumentRootResponse", targetNamespace = "document.acaris.acta.doqui.it", partName = "output")
    public CreaDocumentoFisicoInDocumentRootResponse creaDocumentoFisicoInDocumentRoot(
        @WebParam(name = "creaDocumentoFisicoInDocumentRoot", targetNamespace = "document.acaris.acta.doqui.it", partName = "input")
        CreaDocumentoFisicoInDocumentRoot input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.document.UploadContenutoFisicoResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "uploadContenutoFisicoResponse", targetNamespace = "document.acaris.acta.doqui.it", partName = "output")
    public UploadContenutoFisicoResponse uploadContenutoFisico(
        @WebParam(name = "uploadContenutoFisico", targetNamespace = "document.acaris.acta.doqui.it", partName = "input")
        UploadContenutoFisico input)
        throws AcarisException
    ;

}
