
package com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CUSCSI_SOA_CITTA_METRO_TORINO_PortType", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.ObjectFactory.class,
    com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_anagrafici.ObjectFactory.class,
    com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_assegnazione.ObjectFactory.class,
    com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_indirizzo_dip.ObjectFactory.class,
    com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_organizzazioni_ente.ObjectFactory.class,
    com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_tipologia_org_ente.ObjectFactory.class
})
public interface CUSCSISOACITTAMETROTORINOPortType {


    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_anagrafici.OutputParameters
     */
    @WebMethod(operationName = "GET_DATI_ANAGRAFICI", action = "https://tst-aphr01.csi.it:4444/webservices/SOAProvider/plsql/cuscsi_soa_citta_metro_torino/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_dati_anagrafici/", partName = "body")
    public com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_anagrafici.OutputParameters getDATIANAGRAFICI(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_dati_anagrafici/", partName = "body")
        com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_anagrafici.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_assegnazione.OutputParameters
     */
    @WebMethod(operationName = "GET_DATI_ASSEGNAZIONE", action = "https://tst-aphr01.csi.it:4444/webservices/SOAProvider/plsql/cuscsi_soa_citta_metro_torino/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_dati_assegnazione/", partName = "body")
    public com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_assegnazione.OutputParameters getDATIASSEGNAZIONE(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_dati_assegnazione/", partName = "body")
        com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_assegnazione.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_indirizzo_dip.OutputParameters
     */
    @WebMethod(operationName = "GET_DATI_INDIRIZZO_DIP", action = "https://tst-aphr01.csi.it:4444/webservices/SOAProvider/plsql/cuscsi_soa_citta_metro_torino/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_dati_indirizzo_dip/", partName = "body")
    public com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_indirizzo_dip.OutputParameters getDATIINDIRIZZODIP(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_dati_indirizzo_dip/", partName = "body")
        com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_dati_indirizzo_dip.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_organizzazioni_ente.OutputParameters
     */
    @WebMethod(operationName = "GET_ORGANIZZAZIONI_ENTE", action = "https://tst-aphr01.csi.it:4444/webservices/SOAProvider/plsql/cuscsi_soa_citta_metro_torino/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_organizzazioni_ente/", partName = "body")
    public com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_organizzazioni_ente.OutputParameters getORGANIZZAZIONIENTE(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_organizzazioni_ente/", partName = "body")
        com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_organizzazioni_ente.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_tipologia_org_ente.OutputParameters
     */
    @WebMethod(operationName = "GET_TIPOLOGIA_ORG_ENTE", action = "https://tst-aphr01.csi.it:4444/webservices/SOAProvider/plsql/cuscsi_soa_citta_metro_torino/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_tipologia_org_ente/", partName = "body")
    public com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_tipologia_org_ente.OutputParameters getTIPOLOGIAORGENTE(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/get_tipologia_org_ente/", partName = "body")
        com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.get_tipologia_org_ente.InputParameters body);

}
