
package com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CUSCSI_SOA_CITTA_METRO_TORINO_Service", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", wsdlLocation = "/wsdl/werwre/cuscsi_soa_citta_metro_torino.wsdl")
public class CUSCSISOACITTAMETROTORINOService
    extends Service
{

    private final static URL CUSCSISOACITTAMETROTORINOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSCSISOACITTAMETROTORINOSERVICE_EXCEPTION;
    private final static QName CUSCSISOACITTAMETROTORINOSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", "CUSCSI_SOA_CITTA_METRO_TORINO_Service");

    static {
        CUSCSISOACITTAMETROTORINOSERVICE_WSDL_LOCATION = com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_citta_metro_torino.CUSCSISOACITTAMETROTORINOService.class.getResource("/wsdl/werwre/cuscsi_soa_citta_metro_torino.wsdl");
        WebServiceException e = null;
        if (CUSCSISOACITTAMETROTORINOSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/werwre/cuscsi_soa_citta_metro_torino.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CUSCSISOACITTAMETROTORINOSERVICE_EXCEPTION = e;
    }

    public CUSCSISOACITTAMETROTORINOService() {
        super(__getWsdlLocation(), CUSCSISOACITTAMETROTORINOSERVICE_QNAME);
    }

    public CUSCSISOACITTAMETROTORINOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSCSISOACITTAMETROTORINOSERVICE_QNAME, features);
    }

    public CUSCSISOACITTAMETROTORINOService(URL wsdlLocation) {
        super(wsdlLocation, CUSCSISOACITTAMETROTORINOSERVICE_QNAME);
    }

    public CUSCSISOACITTAMETROTORINOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSCSISOACITTAMETROTORINOSERVICE_QNAME, features);
    }

    public CUSCSISOACITTAMETROTORINOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUSCSISOACITTAMETROTORINOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CUSCSISOACITTAMETROTORINOPortType
     */
    @WebEndpoint(name = "CUSCSI_SOA_CITTA_METRO_TORINO_Port")
    public CUSCSISOACITTAMETROTORINOPortType getCUSCSISOACITTAMETROTORINOPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", "CUSCSI_SOA_CITTA_METRO_TORINO_Port"), CUSCSISOACITTAMETROTORINOPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns CUSCSISOACITTAMETROTORINOPortType
     */
    @WebEndpoint(name = "CUSCSI_SOA_CITTA_METRO_TORINO_Port")
    public CUSCSISOACITTAMETROTORINOPortType getCUSCSISOACITTAMETROTORINOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_citta_metro_torino/", "CUSCSI_SOA_CITTA_METRO_TORINO_Port"), CUSCSISOACITTAMETROTORINOPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSCSISOACITTAMETROTORINOSERVICE_EXCEPTION!= null) {
            throw CUSCSISOACITTAMETROTORINOSERVICE_EXCEPTION;
        }
        return CUSCSISOACITTAMETROTORINOSERVICE_WSDL_LOCATION;
    }

}
