
package it.csi.siac.ricerche.svc._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.csi.siac.documenti.svc._1.RicercaDocumentoEntrataResponse;
import it.csi.siac.documenti.svc._1.RicercaDocumentoSpesaResponse;
import it.csi.siac.documenti.svc._1.RicercaProvvisoriDiCassaResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RicercaService", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.csi.siac.documenti.svc._1.ObjectFactory.class,
    it.csi.siac.integ.data._1.ObjectFactory.class,
    it.csi.siac.ricerche.data._1.ObjectFactory.class,
    it.csi.siac.ricerche.svc._1.ObjectFactory.class
})
public interface RicercaService {


    /**
     * 
     * @param ricercaCapitoloEntrataGestione
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaCapitoloEntrataGestioneResponse
     */
    @WebMethod
    @WebResult(name = "ricercaCapitoloEntrataGestioneResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaCapitoloEntrataGestioneResponse")
    public RicercaCapitoloEntrataGestioneResponse ricercaCapitoloEntrataGestione(
        @WebParam(name = "ricercaCapitoloEntrataGestione", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaCapitoloEntrataGestione")
        RicercaCapitoloEntrataGestione ricercaCapitoloEntrataGestione);

    /**
     * 
     * @param ricercaOrdinativoIncasso
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaOrdinativoIncassoResponse
     */
    @WebMethod
    @WebResult(name = "ricercaOrdinativoIncassoResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaOrdinativoIncassoResponse")
    public RicercaOrdinativoIncassoResponse ricercaOrdinativoIncasso(
        @WebParam(name = "ricercaOrdinativoIncasso", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaOrdinativoIncasso")
        RicercaOrdinativoIncasso ricercaOrdinativoIncasso);

    /**
     * 
     * @param ricercaSinteticaSoggetti
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaSinteticaSoggettiResponse
     */
    @WebMethod
    @WebResult(name = "ricercaSinteticaSoggettiResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaSinteticaSoggettiResponse")
    public RicercaSinteticaSoggettiResponse ricercaSinteticaSoggetti(
        @WebParam(name = "ricercaSinteticaSoggetti", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaSinteticaSoggetti")
        RicercaSinteticaSoggetti ricercaSinteticaSoggetti);

    /**
     * 
     * @param ricercaEstesaOrdinativiSpesa
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaEstesaOrdinativiSpesaResponse
     */
    @WebMethod
    @WebResult(name = "ricercaEstesaOrdinativiSpesaResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaEstesaOrdinativiSpesaResponse")
    public RicercaEstesaOrdinativiSpesaResponse ricercaEstesaOrdinativiSpesa(
        @WebParam(name = "ricercaEstesaOrdinativiSpesa", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaEstesaOrdinativiSpesa")
        RicercaEstesaOrdinativiSpesa ricercaEstesaOrdinativiSpesa);

    /**
     * 
     * @param ricercaDocumentoSpesa
     * @return
     *     returns it.csi.siac.documenti.svc._1.RicercaDocumentoSpesaResponse
     */
    @WebMethod
    @WebResult(name = "ricercaDocumentoSpesaResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaDocumentoSpesaResponse")
    public RicercaDocumentoSpesaResponse ricercaDocumentoSpesa(
        @WebParam(name = "ricercaDocumentoSpesa", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaDocumentoSpesa")
        RicercaDocumentoSpesa ricercaDocumentoSpesa);

    /**
     * 
     * @param ricercaImpegno
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaImpegnoResponse
     */
    @WebMethod
    @WebResult(name = "ricercaImpegnoResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaImpegnoResponse")
    public RicercaImpegnoResponse ricercaImpegno(
        @WebParam(name = "ricercaImpegno", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaImpegno")
        RicercaImpegno ricercaImpegno);

    /**
     * 
     * @param ricercaOrdinativoSpesa
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaOrdinativoSpesaResponse
     */
    @WebMethod
    @WebResult(name = "ricercaOrdinativoSpesaResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaOrdinativoSpesaResponse")
    public RicercaOrdinativoSpesaResponse ricercaOrdinativoSpesa(
        @WebParam(name = "ricercaOrdinativoSpesa", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaOrdinativoSpesa")
        RicercaOrdinativoSpesa ricercaOrdinativoSpesa);

    /**
     * 
     * @param ricercaDettaglioSoggetto
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaDettaglioSoggettiResponse
     */
    @WebMethod
    @WebResult(name = "ricercaDettaglioSoggettoResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaDettaglioSoggettoResponse")
    public RicercaDettaglioSoggettiResponse ricercaDettaglioSoggetto(
        @WebParam(name = "ricercaDettaglioSoggetto", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaDettaglioSoggetto")
        RicercaDettaglioSoggetti ricercaDettaglioSoggetto);

    /**
     * 
     * @param ricercaCapitoloUscitaGestione
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaCapitoloUscitaGestioneResponse
     */
    @WebMethod
    @WebResult(name = "ricercaCapitoloUscitaGestioneResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaCapitoloUscitaGestioneResponse")
    public RicercaCapitoloUscitaGestioneResponse ricercaCapitoloUscitaGestione(
        @WebParam(name = "ricercaCapitoloUscitaGestione", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaCapitoloUscitaGestione")
        RicercaCapitoloUscitaGestione ricercaCapitoloUscitaGestione);

    /**
     * 
     * @param ricercaProvvisoriDiCassa
     * @return
     *     returns it.csi.siac.documenti.svc._1.RicercaProvvisoriDiCassaResponse
     */
    @WebMethod
    @WebResult(name = "ricercaProvvisoriDiCassaResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaProvvisoriDiCassaResponse")
    public RicercaProvvisoriDiCassaResponse ricercaProvvisoriDiCassa(
        @WebParam(name = "ricercaProvvisoriDiCassa", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaProvvisoriDiCassa")
        RicercaProvvisoriDiCassa ricercaProvvisoriDiCassa);

    /**
     * 
     * @param ricercaAccertamento
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaAccertamentoResponse
     */
    @WebMethod
    @WebResult(name = "ricercaAccertamentoResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaAccertamentoResponse")
    public RicercaAccertamentoResponse ricercaAccertamento(
        @WebParam(name = "ricercaAccertamento", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaAccertamento")
        RicercaAccertamento ricercaAccertamento);

    /**
     * 
     * @param ricercaEstesaLiquidazioni
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaEstesaLiquidazioniResponse
     */
    @WebMethod
    @WebResult(name = "ricercaEstesaLiquidazioniResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaEstesaLiquidazioniResponse")
    public RicercaEstesaLiquidazioniResponse ricercaEstesaLiquidazioni(
        @WebParam(name = "ricercaEstesaLiquidazioni", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaEstesaLiquidazioni")
        RicercaEstesaLiquidazioni ricercaEstesaLiquidazioni);

    /**
     * 
     * @param ricercaLiquidazione
     * @return
     *     returns it.csi.siac.ricerche.svc._1.RicercaLiquidazioneResponse
     */
    @WebMethod
    @WebResult(name = "ricercaLiquidazioneResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaLiquidazioneResponse")
    public RicercaLiquidazioneResponse ricercaLiquidazione(
        @WebParam(name = "ricercaLiquidazione", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaLiquidazione")
        RicercaLiquidazione ricercaLiquidazione);

    /**
     * 
     * @param ricercaDocumentoEntrata
     * @return
     *     returns it.csi.siac.documenti.svc._1.RicercaDocumentoEntrataResponse
     */
    @WebMethod
    @WebResult(name = "ricercaDocumentoEntrataResponse", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaDocumentoEntrataResponse")
    public RicercaDocumentoEntrataResponse ricercaDocumentoEntrata(
        @WebParam(name = "ricercaDocumentoEntrata", targetNamespace = "http://siac.csi.it/ricerche/svc/1.0", partName = "ricercaDocumentoEntrata")
        RicercaDocumentoEntrata ricercaDocumentoEntrata);

}
