
package com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_giunta_regionale;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CUSCSI_SOA_GIUNTA_REGIONALE_Service", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_giunta_regionale/", wsdlLocation = "/wsdl/werwre/cuscsi_soa_giunta_regionale.wsdl")
public class CUSCSISOAGIUNTAREGIONALEService
    extends Service
{

    private final static URL CUSCSISOAGIUNTAREGIONALESERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSCSISOAGIUNTAREGIONALESERVICE_EXCEPTION;
    private final static QName CUSCSISOAGIUNTAREGIONALESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_giunta_regionale/", "CUSCSI_SOA_GIUNTA_REGIONALE_Service");

    static {
        CUSCSISOAGIUNTAREGIONALESERVICE_WSDL_LOCATION = com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_giunta_regionale.CUSCSISOAGIUNTAREGIONALEService.class.getResource("/wsdl/werwre/cuscsi_soa_giunta_regionale.wsdl");
        WebServiceException e = null;
        if (CUSCSISOAGIUNTAREGIONALESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/werwre/cuscsi_soa_giunta_regionale.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CUSCSISOAGIUNTAREGIONALESERVICE_EXCEPTION = e;
    }

    public CUSCSISOAGIUNTAREGIONALEService() {
        super(__getWsdlLocation(), CUSCSISOAGIUNTAREGIONALESERVICE_QNAME);
    }

    public CUSCSISOAGIUNTAREGIONALEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSCSISOAGIUNTAREGIONALESERVICE_QNAME, features);
    }

    public CUSCSISOAGIUNTAREGIONALEService(URL wsdlLocation) {
        super(wsdlLocation, CUSCSISOAGIUNTAREGIONALESERVICE_QNAME);
    }

    public CUSCSISOAGIUNTAREGIONALEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSCSISOAGIUNTAREGIONALESERVICE_QNAME, features);
    }

    public CUSCSISOAGIUNTAREGIONALEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUSCSISOAGIUNTAREGIONALEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CUSCSISOAGIUNTAREGIONALEPortType
     */
    @WebEndpoint(name = "CUSCSI_SOA_GIUNTA_REGIONALE_Port")
    public CUSCSISOAGIUNTAREGIONALEPortType getCUSCSISOAGIUNTAREGIONALEPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_giunta_regionale/", "CUSCSI_SOA_GIUNTA_REGIONALE_Port"), CUSCSISOAGIUNTAREGIONALEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns CUSCSISOAGIUNTAREGIONALEPortType
     */
    @WebEndpoint(name = "CUSCSI_SOA_GIUNTA_REGIONALE_Port")
    public CUSCSISOAGIUNTAREGIONALEPortType getCUSCSISOAGIUNTAREGIONALEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_giunta_regionale/", "CUSCSI_SOA_GIUNTA_REGIONALE_Port"), CUSCSISOAGIUNTAREGIONALEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSCSISOAGIUNTAREGIONALESERVICE_EXCEPTION!= null) {
            throw CUSCSISOAGIUNTAREGIONALESERVICE_EXCEPTION;
        }
        return CUSCSISOAGIUNTAREGIONALESERVICE_WSDL_LOCATION;
    }

}
