/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.navigationservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NavigationService", targetNamespace = "navigationservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/navigationWS.wsdl")
public class NavigationService
    extends Service
{

    private final static URL NAVIGATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException NAVIGATIONSERVICE_EXCEPTION;
    private final static QName NAVIGATIONSERVICE_QNAME = new QName("navigationservice.acaris.acta.doqui.it", "NavigationService");

    static {
        NAVIGATIONSERVICE_WSDL_LOCATION = it.doqui.acta.acaris.navigationservice.NavigationService.class.getResource("/wsdl/navigationWS.wsdl");
        WebServiceException e = null;
        if (NAVIGATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/navigationWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        NAVIGATIONSERVICE_EXCEPTION = e;
    }

    public NavigationService() {
        super(__getWsdlLocation(), NAVIGATIONSERVICE_QNAME);
    }

    public NavigationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NAVIGATIONSERVICE_QNAME, features);
    }

    public NavigationService(URL wsdlLocation) {
        super(wsdlLocation, NAVIGATIONSERVICE_QNAME);
    }

    public NavigationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NAVIGATIONSERVICE_QNAME, features);
    }

    public NavigationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NavigationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NavigationServicePort
     */
    @WebEndpoint(name = "NavigationServicePort")
    public NavigationServicePort getNavigationServicePort() {
        return super.getPort(new QName("navigationservice.acaris.acta.doqui.it", "NavigationServicePort"), NavigationServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns NavigationServicePort
     */
    @WebEndpoint(name = "NavigationServicePort")
    public NavigationServicePort getNavigationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("navigationservice.acaris.acta.doqui.it", "NavigationServicePort"), NavigationServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NAVIGATIONSERVICE_EXCEPTION!= null) {
            throw NAVIGATIONSERVICE_EXCEPTION;
        }
        return NAVIGATIONSERVICE_WSDL_LOCATION;
    }

}
