/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.navigationservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.doqui.acta.acaris.archive.GetChildren;
import it.doqui.acta.acaris.archive.GetChildrenResponse;
import it.doqui.acta.acaris.archive.GetDescendants;
import it.doqui.acta.acaris.archive.GetDescendantsResponse;
import it.doqui.acta.acaris.archive.GetFolderParent;
import it.doqui.acta.acaris.archive.GetFolderParentResponse;
import it.doqui.acta.acaris.archive.GetObjectParents;
import it.doqui.acta.acaris.archive.GetObjectParentsResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NavigationServicePort", targetNamespace = "navigationservice.acaris.acta.doqui.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.doqui.acta.acaris.archive.ObjectFactory.class,
    it.doqui.acta.acaris.common.ObjectFactory.class
})
public interface NavigationServicePort {


    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.GetDescendantsResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getDescendantsResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public GetDescendantsResponse getDescendants(
        @WebParam(name = "getDescendants", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        GetDescendants input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.GetChildrenResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getChildrenResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public GetChildrenResponse getChildren(
        @WebParam(name = "getChildren", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        GetChildren input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.GetFolderParentResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getFolderParentResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public GetFolderParentResponse getFolderParent(
        @WebParam(name = "getFolderParent", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        GetFolderParent input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.GetObjectParentsResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getObjectParentsResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public GetObjectParentsResponse getObjectParents(
        @WebParam(name = "getObjectParents", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        GetObjectParents input)
        throws AcarisException
    ;

}
