
package it.eng.auriga.repository2.webservices.getmetadataud;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSGetMetadataUdService", targetNamespace = "http://getmetadataud.webservices.repository2.auriga.eng.it", wsdlLocation = "/wsdl/WSGetMetadataUd.wsdl")
public class WSGetMetadataUdService
    extends Service
{

    private final static URL WSGETMETADATAUDSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSGETMETADATAUDSERVICE_EXCEPTION;
    private final static QName WSGETMETADATAUDSERVICE_QNAME = new QName("http://getmetadataud.webservices.repository2.auriga.eng.it", "WSGetMetadataUdService");

    static {
        WSGETMETADATAUDSERVICE_WSDL_LOCATION = it.eng.auriga.repository2.webservices.getmetadataud.WSGetMetadataUdService.class.getResource("/wsdl/WSGetMetadataUd.wsdl");
        WebServiceException e = null;
        if (WSGETMETADATAUDSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/WSGetMetadataUd.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSGETMETADATAUDSERVICE_EXCEPTION = e;
    }

    public WSGetMetadataUdService() {
        super(__getWsdlLocation(), WSGETMETADATAUDSERVICE_QNAME);
    }

    public WSGetMetadataUdService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSGETMETADATAUDSERVICE_QNAME, features);
    }

    public WSGetMetadataUdService(URL wsdlLocation) {
        super(wsdlLocation, WSGETMETADATAUDSERVICE_QNAME);
    }

    public WSGetMetadataUdService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSGETMETADATAUDSERVICE_QNAME, features);
    }

    public WSGetMetadataUdService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGetMetadataUdService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSIGetMetadataUd
     */
    @WebEndpoint(name = "WSGetMetadataUdPort")
    public WSIGetMetadataUd getWSGetMetadataUdPort() {
        return super.getPort(new QName("http://getmetadataud.webservices.repository2.auriga.eng.it", "WSGetMetadataUdPort"), WSIGetMetadataUd.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns WSIGetMetadataUd
     */
    @WebEndpoint(name = "WSGetMetadataUdPort")
    public WSIGetMetadataUd getWSGetMetadataUdPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://getmetadataud.webservices.repository2.auriga.eng.it", "WSGetMetadataUdPort"), WSIGetMetadataUd.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSGETMETADATAUDSERVICE_EXCEPTION!= null) {
            throw WSGETMETADATAUDSERVICE_EXCEPTION;
        }
        return WSGETMETADATAUDSERVICE_WSDL_LOCATION;
    }

}
