/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2020 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.csi.cpass.cpassbe.mit.client.model.programmi.DatiGeneraliTecnicoEntry;


/**
 * Contenitore per i dati di un intervento
 */
@ApiModel(description = "Contenitore per i dati di un intervento")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class AcquistoEntry   {
  @SerializedName("cui")
  private String cui = null;

  /**
   * Settore F=Forniture, S=Servizi
   */
  public enum SettoreEnum {
    @SerializedName("F")
    F("F"),
    
    @SerializedName("S")
    S("S"),

    @SerializedName("L")
    L("L");

    private String value;

    SettoreEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("settore")
  private SettoreEnum settore = null;

  @SerializedName("codiceInterno")
  private String codiceInterno = null;

  @SerializedName("descrizione")
  private String descrizione = null;

  @SerializedName("anno")
  private Long anno = null;

  @SerializedName("esenteCup")
  private String esenteCup = null;

  @SerializedName("cup")
  private String cup = null;

  @SerializedName("acquistoRicompreso")
  private Long acquistoRicompreso = null;

  @SerializedName("cuiCollegato")
  private String cuiCollegato = null;

  @SerializedName("cpv")
  private String cpv = null;

  @SerializedName("istat")
  private String istat = null;

  @SerializedName("nuts")
  private String nuts = null;

  @SerializedName("quantita")
  private Double quantita = null;

  @SerializedName("unitaMisura")
  private Long unitaMisura = null;

  @SerializedName("priorita")
  private Long priorita = null;

  @SerializedName("lottoFunzionale")
  private String lottoFunzionale = null;

  @SerializedName("durataInMesi")
  private Long durataInMesi = null;

  @SerializedName("nuovoAffidamento")
  private String nuovoAffidamento = null;

  @SerializedName("risorseVincolatePerLegge1")
  private Double risorseVincolatePerLegge1 = null;

  @SerializedName("risorseVincolatePerLegge2")
  private Double risorseVincolatePerLegge2 = null;

  @SerializedName("risorseVincolatePerLeggeSucc")
  private Double risorseVincolatePerLeggeSucc = null;

  @SerializedName("risorseMutuo1")
  private Double risorseMutuo1 = null;

  @SerializedName("risorseMutuo2")
  private Double risorseMutuo2 = null;

  @SerializedName("risorseMutuoSucc")
  private Double risorseMutuoSucc = null;

  @SerializedName("risorsePrivati1")
  private Double risorsePrivati1 = null;

  @SerializedName("risorsePrivati2")
  private Double risorsePrivati2 = null;

  @SerializedName("risorsePrivatiSucc")
  private Double risorsePrivatiSucc = null;

  @SerializedName("risorseBilancio1")
  private Double risorseBilancio1 = null;

  @SerializedName("risorseBilancio2")
  private Double risorseBilancio2 = null;

  @SerializedName("risorseBilancioSucc")
  private Double risorseBilancioSucc = null;

  @SerializedName("risorseArt3_1")
  private Double risorseArt31 = null;

  @SerializedName("risorseArt3_2")
  private Double risorseArt32 = null;

  @SerializedName("risorseArt3_Succ")
  private Double risorseArt3Succ = null;

  @SerializedName("risorseImmobili1")
  private Double risorseImmobili1 = null;

  @SerializedName("risorseImmobili2")
  private Double risorseImmobili2 = null;

  @SerializedName("risorseImmobiliSucc")
  private Double risorseImmobiliSucc = null;

  @SerializedName("risorseAltro1")
  private Double risorseAltro1 = null;

  @SerializedName("risorseAltro2")
  private Double risorseAltro2 = null;

  @SerializedName("risorseAltroSucc")
  private Double risorseAltroSucc = null;

  @SerializedName("speseSostenute")
  private Double speseSostenute = null;

  @SerializedName("tipologiaCapitalePrivato")
  private String tipologiaCapitalePrivato = null;

  @SerializedName("importoRisorseFinanziarie")
  private Double importoRisorseFinanziarie = null;

  @SerializedName("importoRisorseFinanziarieRegionali")
  private Double importoRisorseFinanziarieRegionali = null;

  @SerializedName("importoRisorseFinanziarieAltro")
  private Double importoRisorseFinanziarieAltro = null;

  @SerializedName("meseAvvioProcedura")
  private Long meseAvvioProcedura = null;

  @SerializedName("delega")
  private String delega = null;

  @SerializedName("codiceSoggettoDelegato")
  private String codiceSoggettoDelegato = null;

  @SerializedName("nomeSoggettoDelegato")
  private String nomeSoggettoDelegato = null;

  @SerializedName("variato")
  private Long variato = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("direzioneGenerale")
  private String direzioneGenerale = null;

  @SerializedName("strutturaOperativa")
  private String strutturaOperativa = null;

  @SerializedName("referenteDati")
  private String referenteDati = null;

  @SerializedName("dirigenteResponsabile")
  private String dirigenteResponsabile = null;

  @SerializedName("proceduraAffidamento")
  private Long proceduraAffidamento = null;

  @SerializedName("acquistoVerdi")
  private Long acquistoVerdi = null;

  @SerializedName("normativaRiferimento")
  private String normativaRiferimento = null;

  @SerializedName("oggettoVerdi")
  private String oggettoVerdi = null;

  @SerializedName("cpvVerdi")
  private String cpvVerdi = null;

  @SerializedName("importoNettoIvaVerdi")
  private Double importoNettoIvaVerdi = null;

  @SerializedName("importoIvaVerdi")
  private Double importoIvaVerdi = null;

  @SerializedName("importoTotVerdi")
  private Double importoTotVerdi = null;

  @SerializedName("acquistoMaterialiRiciclati")
  private Long acquistoMaterialiRiciclati = null;

  @SerializedName("oggettoMatRic")
  private String oggettoMatRic = null;

  @SerializedName("cpvMatRic")
  private String cpvMatRic = null;

  @SerializedName("importoNettoIvaMatRic")
  private Double importoNettoIvaMatRic = null;

  @SerializedName("importoIvaMatRic")
  private Double importoIvaMatRic = null;

  @SerializedName("importoTotMatRic")
  private Double importoTotMatRic = null;

  @SerializedName("importoIva1")
  private Double importoIva1 = null;

  @SerializedName("importoIva2")
  private Double importoIva2 = null;

  @SerializedName("importoIvaSucc")
  private Double importoIvaSucc = null;

  @SerializedName("coperturaFinanziaria")
  private String coperturaFinanziaria = null;

  @SerializedName("valutazione")
  private Long valutazione = null;

  @SerializedName("rup")
  private DatiGeneraliTecnicoEntry rup = null;

  @SerializedName("importoCapitalePrivato")
  private Double importoCapitalePrivato = null;

  @SerializedName("importoTotale")
  private Double importoTotale = null;

  public AcquistoEntry cui(String cui) {
    this.cui = cui;
    return this;
  }

   /**
   * Numero intervento CUI (�F� + CodiceFiscale Stazione Appaltante(11 char) + anno (4 char) + progressivo (5 char))
   * @return cui
  **/
  @ApiModelProperty(example = "null", required = true, value = "Numero intervento CUI (�F� + CodiceFiscale Stazione Appaltante(11 char) + anno (4 char) + progressivo (5 char))")
  public String getCui() {
    return cui;
  }

  public void setCui(String cui) {
    this.cui = cui;
  }

  public AcquistoEntry settore(SettoreEnum settore) {
    this.settore = settore;
    return this;
  }

   /**
   * Settore F=Forniture, S=Servizi
   * @return settore
  **/
  @ApiModelProperty(example = "null", required = true, value = "Settore F=Forniture, S=Servizi")
  public SettoreEnum getSettore() {
    return settore;
  }

  public void setSettore(SettoreEnum settore) {
    this.settore = settore;
  }

  public AcquistoEntry codiceInterno(String codiceInterno) {
    this.codiceInterno = codiceInterno;
    return this;
  }

   /**
   * Codice interno attribuito dall'amministrazione
   * @return codiceInterno
  **/
  @ApiModelProperty(example = "null", value = "Codice interno attribuito dall'amministrazione")
  public String getCodiceInterno() {
    return codiceInterno;
  }

  public void setCodiceInterno(String codiceInterno) {
    this.codiceInterno = codiceInterno;
  }

  public AcquistoEntry descrizione(String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Descrizione acquisto
   * @return descrizione
  **/
  @ApiModelProperty(example = "null", required = true, value = "Descrizione acquisto")
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(String descrizione) {
    this.descrizione = descrizione;
  }

  public AcquistoEntry anno(Long anno) {
    this.anno = anno;
    return this;
  }

   /**
   * Annualit� di riferimento avvio procedura di affidamento (1�,2�,3� anno)
   * minimum: 1.0
   * maximum: 3.0
   * @return anno
  **/
  @ApiModelProperty(example = "null", required = true, value = "Annualit� di riferimento avvio procedura di affidamento (1�,2�,3� anno)")
  public Long getAnno() {
    return anno;
  }

  public void setAnno(Long anno) {
    this.anno = anno;
  }

  public AcquistoEntry esenteCup(String esenteCup) {
    this.esenteCup = esenteCup;
    return this;
  }

   /**
   * Esente dalla richiesta CUP? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)
   * @return esenteCup
  **/
  @ApiModelProperty(example = "null", value = "Esente dalla richiesta CUP? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)")
  public String getEsenteCup() {
    return esenteCup;
  }

  public void setEsenteCup(String esenteCup) {
    this.esenteCup = esenteCup;
  }

  public AcquistoEntry cup(String cup) {
    this.cup = cup;
    return this;
  }

   /**
   * Codice CUP di progetto (assegnato da CIPE)
   * @return cup
  **/
  @ApiModelProperty(example = "null", value = "Codice CUP di progetto (assegnato da CIPE)")
  public String getCup() {
    return cup;
  }

  public void setCup(String cup) {
    this.cup = cup;
  }

  public AcquistoEntry acquistoRicompreso(Long acquistoRicompreso) {
    this.acquistoRicompreso = acquistoRicompreso;
    return this;
  }

   /**
   * Acquisto ricompreso nell'importo di lavoro o altra acquisizione nel programma? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=AcquistoRicompreso)
   * @return acquistoRicompreso
  **/
  @ApiModelProperty(example = "null", value = "Acquisto ricompreso nell'importo di lavoro o altra acquisizione nel programma? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=AcquistoRicompreso)")
  public Long getAcquistoRicompreso() {
    return acquistoRicompreso;
  }

  public void setAcquistoRicompreso(Long acquistoRicompreso) {
    this.acquistoRicompreso = acquistoRicompreso;
  }

  public AcquistoEntry cuiCollegato(String cuiCollegato) {
    this.cuiCollegato = cuiCollegato;
    return this;
  }

   /**
   * Codice CUI dell'intervento collegato
   * @return cuiCollegato
  **/
  @ApiModelProperty(example = "null", value = "Codice CUI dell'intervento collegato")
  public String getCuiCollegato() {
    return cuiCollegato;
  }

  public void setCuiCollegato(String cuiCollegato) {
    this.cuiCollegato = cuiCollegato;
  }

  public AcquistoEntry cpv(String cpv) {
    this.cpv = cpv;
    return this;
  }

   /**
   * Codice CPV
   * @return cpv
  **/
  @ApiModelProperty(example = "null", value = "Codice CPV")
  public String getCpv() {
    return cpv;
  }

  public void setCpv(String cpv) {
    this.cpv = cpv;
  }

  public AcquistoEntry istat(String istat) {
    this.istat = istat;
    return this;
  }

   /**
   * Localizzazione - Codice ISTAT del Comune
   * @return istat
  **/
  @ApiModelProperty(example = "null", value = "Localizzazione - Codice ISTAT del Comune")
  public String getIstat() {
    return istat;
  }

  public void setIstat(String istat) {
    this.istat = istat;
  }

  public AcquistoEntry nuts(String nuts) {
    this.nuts = nuts;
    return this;
  }

   /**
   * Localizzazione - NUTS
   * @return nuts
  **/
  @ApiModelProperty(example = "null", value = "Localizzazione - NUTS")
  public String getNuts() {
    return nuts;
  }

  public void setNuts(String nuts) {
    this.nuts = nuts;
  }

  public AcquistoEntry quantita(Double quantita) {
    this.quantita = quantita;
    return this;
  }

   /**
   * Quantit�
   * @return quantita
  **/
  @ApiModelProperty(example = "null", value = "Quantit�")
  public Double getQuantita() {
    return quantita;
  }

  public void setQuantita(Double quantita) {
    this.quantita = quantita;
  }

  public AcquistoEntry unitaMisura(Long unitaMisura) {
    this.unitaMisura = unitaMisura;
    return this;
  }

   /**
   * Unit� di misura (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=UnitaMisura)
   * @return unitaMisura
  **/
  @ApiModelProperty(example = "null", value = "Unit� di misura (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=UnitaMisura)")
  public Long getUnitaMisura() {
    return unitaMisura;
  }

  public void setUnitaMisura(Long unitaMisura) {
    this.unitaMisura = unitaMisura;
  }

  public AcquistoEntry priorita(Long priorita) {
    this.priorita = priorita;
    return this;
  }

   /**
   * Livello di Priorit� (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Priorita)
   * @return priorita
  **/
  @ApiModelProperty(example = "null", value = "Livello di Priorit� (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Priorita)")
  public Long getPriorita() {
    return priorita;
  }

  public void setPriorita(Long priorita) {
    this.priorita = priorita;
  }

  public AcquistoEntry lottoFunzionale(String lottoFunzionale) {
    this.lottoFunzionale = lottoFunzionale;
    return this;
  }

   /**
   * Lotto funzionale? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)
   * @return lottoFunzionale
  **/
  @ApiModelProperty(example = "null", value = "Lotto funzionale? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)")
  public String getLottoFunzionale() {
    return lottoFunzionale;
  }

  public void setLottoFunzionale(String lottoFunzionale) {
    this.lottoFunzionale = lottoFunzionale;
  }

  public AcquistoEntry durataInMesi(Long durataInMesi) {
    this.durataInMesi = durataInMesi;
    return this;
  }

   /**
   * Durata del contratto (mesi)
   * @return durataInMesi
  **/
  @ApiModelProperty(example = "null", value = "Durata del contratto (mesi)")
  public Long getDurataInMesi() {
    return durataInMesi;
  }

  public void setDurataInMesi(Long durataInMesi) {
    this.durataInMesi = durataInMesi;
  }

  public AcquistoEntry nuovoAffidamento(String nuovoAffidamento) {
    this.nuovoAffidamento = nuovoAffidamento;
    return this;
  }

   /**
   * Nuovo affidamento contratto in essere? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)
   * @return nuovoAffidamento
  **/
  @ApiModelProperty(example = "null", value = "Nuovo affidamento contratto in essere? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)")
  public String getNuovoAffidamento() {
    return nuovoAffidamento;
  }

  public void setNuovoAffidamento(String nuovoAffidamento) {
    this.nuovoAffidamento = nuovoAffidamento;
  }

  public AcquistoEntry risorseVincolatePerLegge1(Double risorseVincolatePerLegge1) {
    this.risorseVincolatePerLegge1 = risorseVincolatePerLegge1;
    return this;
  }

   /**
   * Risorse derivanti da entrate aventi destinazione vincolata per legge - Primo anno
   * @return risorseVincolatePerLegge1
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da entrate aventi destinazione vincolata per legge - Primo anno")
  public Double getRisorseVincolatePerLegge1() {
    return risorseVincolatePerLegge1;
  }

  public void setRisorseVincolatePerLegge1(Double risorseVincolatePerLegge1) {
    this.risorseVincolatePerLegge1 = risorseVincolatePerLegge1;
  }

  public AcquistoEntry risorseVincolatePerLegge2(Double risorseVincolatePerLegge2) {
    this.risorseVincolatePerLegge2 = risorseVincolatePerLegge2;
    return this;
  }

   /**
   * Risorse derivanti da entrate aventi destinazione vincolata per legge - Secondo anno
   * @return risorseVincolatePerLegge2
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da entrate aventi destinazione vincolata per legge - Secondo anno")
  public Double getRisorseVincolatePerLegge2() {
    return risorseVincolatePerLegge2;
  }

  public void setRisorseVincolatePerLegge2(Double risorseVincolatePerLegge2) {
    this.risorseVincolatePerLegge2 = risorseVincolatePerLegge2;
  }

  public AcquistoEntry risorseVincolatePerLeggeSucc(Double risorseVincolatePerLeggeSucc) {
    this.risorseVincolatePerLeggeSucc = risorseVincolatePerLeggeSucc;
    return this;
  }

   /**
   * Risorse derivanti da entrate aventi destinazione vincolata per legge - Annualit� successive
   * @return risorseVincolatePerLeggeSucc
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da entrate aventi destinazione vincolata per legge - Annualit� successive")
  public Double getRisorseVincolatePerLeggeSucc() {
    return risorseVincolatePerLeggeSucc;
  }

  public void setRisorseVincolatePerLeggeSucc(Double risorseVincolatePerLeggeSucc) {
    this.risorseVincolatePerLeggeSucc = risorseVincolatePerLeggeSucc;
  }

  public AcquistoEntry risorseMutuo1(Double risorseMutuo1) {
    this.risorseMutuo1 = risorseMutuo1;
    return this;
  }

   /**
   * Risorse derivanti da entrate acquisite mediante contrazione di mutuo - Primo anno
   * @return risorseMutuo1
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da entrate acquisite mediante contrazione di mutuo - Primo anno")
  public Double getRisorseMutuo1() {
    return risorseMutuo1;
  }

  public void setRisorseMutuo1(Double risorseMutuo1) {
    this.risorseMutuo1 = risorseMutuo1;
  }

  public AcquistoEntry risorseMutuo2(Double risorseMutuo2) {
    this.risorseMutuo2 = risorseMutuo2;
    return this;
  }

   /**
   * Risorse derivanti da entrate acquisite mediante contrazione di mutuo - Secondo anno
   * @return risorseMutuo2
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da entrate acquisite mediante contrazione di mutuo - Secondo anno")
  public Double getRisorseMutuo2() {
    return risorseMutuo2;
  }

  public void setRisorseMutuo2(Double risorseMutuo2) {
    this.risorseMutuo2 = risorseMutuo2;
  }

  public AcquistoEntry risorseMutuoSucc(Double risorseMutuoSucc) {
    this.risorseMutuoSucc = risorseMutuoSucc;
    return this;
  }

   /**
   * Risorse derivanti da entrate acquisite mediante contrazione di mutuo - Annualit� successive
   * @return risorseMutuoSucc
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da entrate acquisite mediante contrazione di mutuo - Annualit� successive")
  public Double getRisorseMutuoSucc() {
    return risorseMutuoSucc;
  }

  public void setRisorseMutuoSucc(Double risorseMutuoSucc) {
    this.risorseMutuoSucc = risorseMutuoSucc;
  }

  public AcquistoEntry risorsePrivati1(Double risorsePrivati1) {
    this.risorsePrivati1 = risorsePrivati1;
    return this;
  }

   /**
   * Risorse acquisite mediante apporti di capitale privato - Primo anno
   * @return risorsePrivati1
  **/
  @ApiModelProperty(example = "null", value = "Risorse acquisite mediante apporti di capitale privato - Primo anno")
  public Double getRisorsePrivati1() {
    return risorsePrivati1;
  }

  public void setRisorsePrivati1(Double risorsePrivati1) {
    this.risorsePrivati1 = risorsePrivati1;
  }

  public AcquistoEntry risorsePrivati2(Double risorsePrivati2) {
    this.risorsePrivati2 = risorsePrivati2;
    return this;
  }

   /**
   * Risorse acquisite mediante apporti di capitale privato - Secondo anno
   * @return risorsePrivati2
  **/
  @ApiModelProperty(example = "null", value = "Risorse acquisite mediante apporti di capitale privato - Secondo anno")
  public Double getRisorsePrivati2() {
    return risorsePrivati2;
  }

  public void setRisorsePrivati2(Double risorsePrivati2) {
    this.risorsePrivati2 = risorsePrivati2;
  }

  public AcquistoEntry risorsePrivatiSucc(Double risorsePrivatiSucc) {
    this.risorsePrivatiSucc = risorsePrivatiSucc;
    return this;
  }

   /**
   * Risorse acquisite mediante apporti di capitale privato - Annualit� successive
   * @return risorsePrivatiSucc
  **/
  @ApiModelProperty(example = "null", value = "Risorse acquisite mediante apporti di capitale privato - Annualit� successive")
  public Double getRisorsePrivatiSucc() {
    return risorsePrivatiSucc;
  }

  public void setRisorsePrivatiSucc(Double risorsePrivatiSucc) {
    this.risorsePrivatiSucc = risorsePrivatiSucc;
  }

  public AcquistoEntry risorseBilancio1(Double risorseBilancio1) {
    this.risorseBilancio1 = risorseBilancio1;
    return this;
  }

   /**
   * Stanziamenti di bilancio - Primo anno
   * @return risorseBilancio1
  **/
  @ApiModelProperty(example = "null", value = "Stanziamenti di bilancio - Primo anno")
  public Double getRisorseBilancio1() {
    return risorseBilancio1;
  }

  public void setRisorseBilancio1(Double risorseBilancio1) {
    this.risorseBilancio1 = risorseBilancio1;
  }

  public AcquistoEntry risorseBilancio2(Double risorseBilancio2) {
    this.risorseBilancio2 = risorseBilancio2;
    return this;
  }

   /**
   * Stanziamenti di bilancio - Secondo anno
   * @return risorseBilancio2
  **/
  @ApiModelProperty(example = "null", value = "Stanziamenti di bilancio - Secondo anno")
  public Double getRisorseBilancio2() {
    return risorseBilancio2;
  }

  public void setRisorseBilancio2(Double risorseBilancio2) {
    this.risorseBilancio2 = risorseBilancio2;
  }

  public AcquistoEntry risorseBilancioSucc(Double risorseBilancioSucc) {
    this.risorseBilancioSucc = risorseBilancioSucc;
    return this;
  }

   /**
   * Stanziamenti di bilancio - Annualit� successive
   * @return risorseBilancioSucc
  **/
  @ApiModelProperty(example = "null", value = "Stanziamenti di bilancio - Annualit� successive")
  public Double getRisorseBilancioSucc() {
    return risorseBilancioSucc;
  }

  public void setRisorseBilancioSucc(Double risorseBilancioSucc) {
    this.risorseBilancioSucc = risorseBilancioSucc;
  }

  public AcquistoEntry risorseArt31(Double risorseArt31) {
    this.risorseArt31 = risorseArt31;
    return this;
  }

   /**
   * Finanziamenti art. 3 DL 310/1990 - Primo anno
   * @return risorseArt31
  **/
  @ApiModelProperty(example = "null", value = "Finanziamenti art. 3 DL 310/1990 - Primo anno")
  public Double getRisorseArt31() {
    return risorseArt31;
  }

  public void setRisorseArt31(Double risorseArt31) {
    this.risorseArt31 = risorseArt31;
  }

  public AcquistoEntry risorseArt32(Double risorseArt32) {
    this.risorseArt32 = risorseArt32;
    return this;
  }

   /**
   * Finanziamenti art. 3 DL 310/1990 - Secondo anno
   * @return risorseArt32
  **/
  @ApiModelProperty(example = "null", value = "Finanziamenti art. 3 DL 310/1990 - Secondo anno")
  public Double getRisorseArt32() {
    return risorseArt32;
  }

  public void setRisorseArt32(Double risorseArt32) {
    this.risorseArt32 = risorseArt32;
  }

  public AcquistoEntry risorseArt3Succ(Double risorseArt3Succ) {
    this.risorseArt3Succ = risorseArt3Succ;
    return this;
  }

   /**
   * Finanziamenti art. 3 DL 310/1990 - Annualit� successive
   * @return risorseArt3Succ
  **/
  @ApiModelProperty(example = "null", value = "Finanziamenti art. 3 DL 310/1990 - Annualit� successive")
  public Double getRisorseArt3Succ() {
    return risorseArt3Succ;
  }

  public void setRisorseArt3Succ(Double risorseArt3Succ) {
    this.risorseArt3Succ = risorseArt3Succ;
  }

  public AcquistoEntry risorseImmobili1(Double risorseImmobili1) {
    this.risorseImmobili1 = risorseImmobili1;
    return this;
  }

   /**
   * Risorse derivanti da trasferimento immobili - Primo anno
   * @return risorseImmobili1
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da trasferimento immobili - Primo anno")
  public Double getRisorseImmobili1() {
    return risorseImmobili1;
  }

  public void setRisorseImmobili1(Double risorseImmobili1) {
    this.risorseImmobili1 = risorseImmobili1;
  }

  public AcquistoEntry risorseImmobili2(Double risorseImmobili2) {
    this.risorseImmobili2 = risorseImmobili2;
    return this;
  }

   /**
   * Risorse derivanti da trasferimento immobili - Secondo anno
   * @return risorseImmobili2
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da trasferimento immobili - Secondo anno")
  public Double getRisorseImmobili2() {
    return risorseImmobili2;
  }

  public void setRisorseImmobili2(Double risorseImmobili2) {
    this.risorseImmobili2 = risorseImmobili2;
  }

  public AcquistoEntry risorseImmobiliSucc(Double risorseImmobiliSucc) {
    this.risorseImmobiliSucc = risorseImmobiliSucc;
    return this;
  }

   /**
   * Risorse derivanti da trasferimento immobili - Annualit� successive
   * @return risorseImmobiliSucc
  **/
  @ApiModelProperty(example = "null", value = "Risorse derivanti da trasferimento immobili - Annualit� successive")
  public Double getRisorseImmobiliSucc() {
    return risorseImmobiliSucc;
  }

  public void setRisorseImmobiliSucc(Double risorseImmobiliSucc) {
    this.risorseImmobiliSucc = risorseImmobiliSucc;
  }

  public AcquistoEntry risorseAltro1(Double risorseAltro1) {
    this.risorseAltro1 = risorseAltro1;
    return this;
  }

   /**
   * Altra tipologia - Primo anno
   * @return risorseAltro1
  **/
  @ApiModelProperty(example = "null", value = "Altra tipologia - Primo anno")
  public Double getRisorseAltro1() {
    return risorseAltro1;
  }

  public void setRisorseAltro1(Double risorseAltro1) {
    this.risorseAltro1 = risorseAltro1;
  }

  public AcquistoEntry risorseAltro2(Double risorseAltro2) {
    this.risorseAltro2 = risorseAltro2;
    return this;
  }

   /**
   * Altra tipologia - Secondo anno
   * @return risorseAltro2
  **/
  @ApiModelProperty(example = "null", value = "Altra tipologia - Secondo anno")
  public Double getRisorseAltro2() {
    return risorseAltro2;
  }

  public void setRisorseAltro2(Double risorseAltro2) {
    this.risorseAltro2 = risorseAltro2;
  }

  public AcquistoEntry risorseAltroSucc(Double risorseAltroSucc) {
    this.risorseAltroSucc = risorseAltroSucc;
    return this;
  }

   /**
   * Altra tipologia - Annualit� successive
   * @return risorseAltroSucc
  **/
  @ApiModelProperty(example = "null", value = "Altra tipologia - Annualit� successive")
  public Double getRisorseAltroSucc() {
    return risorseAltroSucc;
  }

  public void setRisorseAltroSucc(Double risorseAltroSucc) {
    this.risorseAltroSucc = risorseAltroSucc;
  }

  public AcquistoEntry speseSostenute(Double speseSostenute) {
    this.speseSostenute = speseSostenute;
    return this;
  }

   /**
   * Spese gi� sostenute
   * @return speseSostenute
  **/
  @ApiModelProperty(example = "null", value = "Spese gi� sostenute")
  public Double getSpeseSostenute() {
    return speseSostenute;
  }

  public void setSpeseSostenute(Double speseSostenute) {
    this.speseSostenute = speseSostenute;
  }

  public AcquistoEntry tipologiaCapitalePrivato(String tipologiaCapitalePrivato) {
    this.tipologiaCapitalePrivato = tipologiaCapitalePrivato;
    return this;
  }

   /**
   * Tipologia apporto di capitale privato (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=TipologiaCapitalePrivato)
   * @return tipologiaCapitalePrivato
  **/
  @ApiModelProperty(example = "null", value = "Tipologia apporto di capitale privato (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=TipologiaCapitalePrivato)")
  public String getTipologiaCapitalePrivato() {
    return tipologiaCapitalePrivato;
  }

  public void setTipologiaCapitalePrivato(String tipologiaCapitalePrivato) {
    this.tipologiaCapitalePrivato = tipologiaCapitalePrivato;
  }

  public AcquistoEntry importoRisorseFinanziarie(Double importoRisorseFinanziarie) {
    this.importoRisorseFinanziarie = importoRisorseFinanziarie;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo risorse finanziarie stato/UE
   * @return importoRisorseFinanziarie
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo risorse finanziarie stato/UE")
  public Double getImportoRisorseFinanziarie() {
    return importoRisorseFinanziarie;
  }

  public void setImportoRisorseFinanziarie(Double importoRisorseFinanziarie) {
    this.importoRisorseFinanziarie = importoRisorseFinanziarie;
  }

  public AcquistoEntry importoRisorseFinanziarieRegionali(Double importoRisorseFinanziarieRegionali) {
    this.importoRisorseFinanziarieRegionali = importoRisorseFinanziarieRegionali;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo risorse finanziarie regionali
   * @return importoRisorseFinanziarieRegionali
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo risorse finanziarie regionali")
  public Double getImportoRisorseFinanziarieRegionali() {
    return importoRisorseFinanziarieRegionali;
  }

  public void setImportoRisorseFinanziarieRegionali(Double importoRisorseFinanziarieRegionali) {
    this.importoRisorseFinanziarieRegionali = importoRisorseFinanziarieRegionali;
  }

  public AcquistoEntry importoRisorseFinanziarieAltro(Double importoRisorseFinanziarieAltro) {
    this.importoRisorseFinanziarieAltro = importoRisorseFinanziarieAltro;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo risorse finanziarie altro
   * @return importoRisorseFinanziarieAltro
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo risorse finanziarie altro")
  public Double getImportoRisorseFinanziarieAltro() {
    return importoRisorseFinanziarieAltro;
  }

  public void setImportoRisorseFinanziarieAltro(Double importoRisorseFinanziarieAltro) {
    this.importoRisorseFinanziarieAltro = importoRisorseFinanziarieAltro;
  }

  public AcquistoEntry meseAvvioProcedura(Long meseAvvioProcedura) {
    this.meseAvvioProcedura = meseAvvioProcedura;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Mese previsto per avvio procedura contrattuale
   * @return meseAvvioProcedura
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Mese previsto per avvio procedura contrattuale")
  public Long getMeseAvvioProcedura() {
    return meseAvvioProcedura;
  }

  public void setMeseAvvioProcedura(Long meseAvvioProcedura) {
    this.meseAvvioProcedura = meseAvvioProcedura;
  }

  public AcquistoEntry delega(String delega) {
    this.delega = delega;
    return this;
  }

   /**
   * Si intende delegare la procedura di affidamento? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)
   * @return delega
  **/
  @ApiModelProperty(example = "null", value = "Si intende delegare la procedura di affidamento? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)")
  public String getDelega() {
    return delega;
  }

  public void setDelega(String delega) {
    this.delega = delega;
  }

  public AcquistoEntry codiceSoggettoDelegato(String codiceSoggettoDelegato) {
    this.codiceSoggettoDelegato = codiceSoggettoDelegato;
    return this;
  }

   /**
   * Codice AUSA Centrale di Committenza o Soggetto Aggregatore
   * @return codiceSoggettoDelegato
  **/
  @ApiModelProperty(example = "null", value = "Codice AUSA Centrale di Committenza o Soggetto Aggregatore")
  public String getCodiceSoggettoDelegato() {
    return codiceSoggettoDelegato;
  }

  public void setCodiceSoggettoDelegato(String codiceSoggettoDelegato) {
    this.codiceSoggettoDelegato = codiceSoggettoDelegato;
  }

  public AcquistoEntry nomeSoggettoDelegato(String nomeSoggettoDelegato) {
    this.nomeSoggettoDelegato = nomeSoggettoDelegato;
    return this;
  }

   /**
   * Denominazione Centrale di Committenza o Soggetto Aggregatore
   * @return nomeSoggettoDelegato
  **/
  @ApiModelProperty(example = "null", value = "Denominazione Centrale di Committenza o Soggetto Aggregatore")
  public String getNomeSoggettoDelegato() {
    return nomeSoggettoDelegato;
  }

  public void setNomeSoggettoDelegato(String nomeSoggettoDelegato) {
    this.nomeSoggettoDelegato = nomeSoggettoDelegato;
  }

  public AcquistoEntry variato(Long variato) {
    this.variato = variato;
    return this;
  }

   /**
   * Intervento variato a seguito di modifica programma (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=VariatoAcquisti)
   * @return variato
  **/
  @ApiModelProperty(example = "null", value = "Intervento variato a seguito di modifica programma (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=VariatoAcquisti)")
  public Long getVariato() {
    return variato;
  }

  public void setVariato(Long variato) {
    this.variato = variato;
  }

  public AcquistoEntry note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Eventuali note
   * @return note
  **/
  @ApiModelProperty(example = "null", value = "Eventuali note")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public AcquistoEntry direzioneGenerale(String direzioneGenerale) {
    this.direzioneGenerale = direzioneGenerale;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Direzione generale
   * @return direzioneGenerale
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Direzione generale")
  public String getDirezioneGenerale() {
    return direzioneGenerale;
  }

  public void setDirezioneGenerale(String direzioneGenerale) {
    this.direzioneGenerale = direzioneGenerale;
  }

  public AcquistoEntry strutturaOperativa(String strutturaOperativa) {
    this.strutturaOperativa = strutturaOperativa;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Struttura operativa
   * @return strutturaOperativa
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Struttura operativa")
  public String getStrutturaOperativa() {
    return strutturaOperativa;
  }

  public void setStrutturaOperativa(String strutturaOperativa) {
    this.strutturaOperativa = strutturaOperativa;
  }

  public AcquistoEntry referenteDati(String referenteDati) {
    this.referenteDati = referenteDati;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Referente per i dati comunicati
   * @return referenteDati
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Referente per i dati comunicati")
  public String getReferenteDati() {
    return referenteDati;
  }

  public void setReferenteDati(String referenteDati) {
    this.referenteDati = referenteDati;
  }

  public AcquistoEntry dirigenteResponsabile(String dirigenteResponsabile) {
    this.dirigenteResponsabile = dirigenteResponsabile;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Dirigente responsabile d'ufficio
   * @return dirigenteResponsabile
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Dirigente responsabile d'ufficio")
  public String getDirigenteResponsabile() {
    return dirigenteResponsabile;
  }

  public void setDirigenteResponsabile(String dirigenteResponsabile) {
    this.dirigenteResponsabile = dirigenteResponsabile;
  }

  public AcquistoEntry proceduraAffidamento(Long proceduraAffidamento) {
    this.proceduraAffidamento = proceduraAffidamento;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Procedura affidamento (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=ProceduraAffidamento)
   * @return proceduraAffidamento
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Procedura affidamento (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=ProceduraAffidamento)")
  public Long getProceduraAffidamento() {
    return proceduraAffidamento;
  }

  public void setProceduraAffidamento(Long proceduraAffidamento) {
    this.proceduraAffidamento = proceduraAffidamento;
  }

  public AcquistoEntry acquistoVerdi(Long acquistoVerdi) {
    this.acquistoVerdi = acquistoVerdi;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Sono presenti acq. verdi art. 34 Dlgs 50/2016 (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Acquisto)
   * @return acquistoVerdi
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Sono presenti acq. verdi art. 34 Dlgs 50/2016 (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Acquisto)")
  public Long getAcquistoVerdi() {
    return acquistoVerdi;
  }

  public void setAcquistoVerdi(Long acquistoVerdi) {
    this.acquistoVerdi = acquistoVerdi;
  }

  public AcquistoEntry normativaRiferimento(String normativaRiferimento) {
    this.normativaRiferimento = normativaRiferimento;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Normativa di riferimento
   * @return normativaRiferimento
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Normativa di riferimento")
  public String getNormativaRiferimento() {
    return normativaRiferimento;
  }

  public void setNormativaRiferimento(String normativaRiferimento) {
    this.normativaRiferimento = normativaRiferimento;
  }

  public AcquistoEntry oggettoVerdi(String oggettoVerdi) {
    this.oggettoVerdi = oggettoVerdi;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Oggetto verdi
   * @return oggettoVerdi
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Oggetto verdi")
  public String getOggettoVerdi() {
    return oggettoVerdi;
  }

  public void setOggettoVerdi(String oggettoVerdi) {
    this.oggettoVerdi = oggettoVerdi;
  }

  public AcquistoEntry cpvVerdi(String cpvVerdi) {
    this.cpvVerdi = cpvVerdi;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Codice CPV verdi
   * @return cpvVerdi
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Codice CPV verdi")
  public String getCpvVerdi() {
    return cpvVerdi;
  }

  public void setCpvVerdi(String cpvVerdi) {
    this.cpvVerdi = cpvVerdi;
  }

  public AcquistoEntry importoNettoIvaVerdi(Double importoNettoIvaVerdi) {
    this.importoNettoIvaVerdi = importoNettoIvaVerdi;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo al netto dell'IVA verdi
   * @return importoNettoIvaVerdi
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo al netto dell'IVA verdi")
  public Double getImportoNettoIvaVerdi() {
    return importoNettoIvaVerdi;
  }

  public void setImportoNettoIvaVerdi(Double importoNettoIvaVerdi) {
    this.importoNettoIvaVerdi = importoNettoIvaVerdi;
  }

  public AcquistoEntry importoIvaVerdi(Double importoIvaVerdi) {
    this.importoIvaVerdi = importoIvaVerdi;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA verdi
   * @return importoIvaVerdi
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA verdi")
  public Double getImportoIvaVerdi() {
    return importoIvaVerdi;
  }

  public void setImportoIvaVerdi(Double importoIvaVerdi) {
    this.importoIvaVerdi = importoIvaVerdi;
  }

  public AcquistoEntry importoTotVerdi(Double importoTotVerdi) {
    this.importoTotVerdi = importoTotVerdi;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo Totale verdi
   * @return importoTotVerdi
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo Totale verdi")
  public Double getImportoTotVerdi() {
    return importoTotVerdi;
  }

  public void setImportoTotVerdi(Double importoTotVerdi) {
    this.importoTotVerdi = importoTotVerdi;
  }

  public AcquistoEntry acquistoMaterialiRiciclati(Long acquistoMaterialiRiciclati) {
    this.acquistoMaterialiRiciclati = acquistoMaterialiRiciclati;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Acquisto di beni realizzati con materiali riciclati? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Acquisto)
   * @return acquistoMaterialiRiciclati
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Acquisto di beni realizzati con materiali riciclati? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Acquisto)")
  public Long getAcquistoMaterialiRiciclati() {
    return acquistoMaterialiRiciclati;
  }

  public void setAcquistoMaterialiRiciclati(Long acquistoMaterialiRiciclati) {
    this.acquistoMaterialiRiciclati = acquistoMaterialiRiciclati;
  }

  public AcquistoEntry oggettoMatRic(String oggettoMatRic) {
    this.oggettoMatRic = oggettoMatRic;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Oggetto materiali riciclati
   * @return oggettoMatRic
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Oggetto materiali riciclati")
  public String getOggettoMatRic() {
    return oggettoMatRic;
  }

  public void setOggettoMatRic(String oggettoMatRic) {
    this.oggettoMatRic = oggettoMatRic;
  }

  public AcquistoEntry cpvMatRic(String cpvMatRic) {
    this.cpvMatRic = cpvMatRic;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Codice CPV materiali riciclati
   * @return cpvMatRic
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Codice CPV materiali riciclati")
  public String getCpvMatRic() {
    return cpvMatRic;
  }

  public void setCpvMatRic(String cpvMatRic) {
    this.cpvMatRic = cpvMatRic;
  }

  public AcquistoEntry importoNettoIvaMatRic(Double importoNettoIvaMatRic) {
    this.importoNettoIvaMatRic = importoNettoIvaMatRic;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo al netto dell'IVA materiali riciclati
   * @return importoNettoIvaMatRic
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo al netto dell'IVA materiali riciclati")
  public Double getImportoNettoIvaMatRic() {
    return importoNettoIvaMatRic;
  }

  public void setImportoNettoIvaMatRic(Double importoNettoIvaMatRic) {
    this.importoNettoIvaMatRic = importoNettoIvaMatRic;
  }

  public AcquistoEntry importoIvaMatRic(Double importoIvaMatRic) {
    this.importoIvaMatRic = importoIvaMatRic;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA materiali riciclati
   * @return importoIvaMatRic
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA materiali riciclati")
  public Double getImportoIvaMatRic() {
    return importoIvaMatRic;
  }

  public void setImportoIvaMatRic(Double importoIvaMatRic) {
    this.importoIvaMatRic = importoIvaMatRic;
  }

  public AcquistoEntry importoTotMatRic(Double importoTotMatRic) {
    this.importoTotMatRic = importoTotMatRic;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo Totale materiali riciclati
   * @return importoTotMatRic
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo Totale materiali riciclati")
  public Double getImportoTotMatRic() {
    return importoTotMatRic;
  }

  public void setImportoTotMatRic(Double importoTotMatRic) {
    this.importoTotMatRic = importoTotMatRic;
  }

  public AcquistoEntry importoIva1(Double importoIva1) {
    this.importoIva1 = importoIva1;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA - Primo anno
   * @return importoIva1
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA - Primo anno")
  public Double getImportoIva1() {
    return importoIva1;
  }

  public void setImportoIva1(Double importoIva1) {
    this.importoIva1 = importoIva1;
  }

  public AcquistoEntry importoIva2(Double importoIva2) {
    this.importoIva2 = importoIva2;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA - Secondo anno
   * @return importoIva2
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA - Secondo anno")
  public Double getImportoIva2() {
    return importoIva2;
  }

  public void setImportoIva2(Double importoIva2) {
    this.importoIva2 = importoIva2;
  }

  public AcquistoEntry importoIvaSucc(Double importoIvaSucc) {
    this.importoIvaSucc = importoIvaSucc;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA - Annualit� successive
   * @return importoIvaSucc
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Importo IVA - Annualit� successive")
  public Double getImportoIvaSucc() {
    return importoIvaSucc;
  }

  public void setImportoIvaSucc(Double importoIvaSucc) {
    this.importoIvaSucc = importoIvaSucc;
  }

  public AcquistoEntry coperturaFinanziaria(String coperturaFinanziaria) {
    this.coperturaFinanziaria = coperturaFinanziaria;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] L'acquisto ha copertura finanziaria? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)
   * @return coperturaFinanziaria
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] L'acquisto ha copertura finanziaria? (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)")
  public String getCoperturaFinanziaria() {
    return coperturaFinanziaria;
  }

  public void setCoperturaFinanziaria(String coperturaFinanziaria) {
    this.coperturaFinanziaria = coperturaFinanziaria;
  }

  public AcquistoEntry valutazione(Long valutazione) {
    this.valutazione = valutazione;
    return this;
  }

   /**
   * [Attributo aggiuntivo, previsto in ambiti regionali] Valutazione del responsabile dl programma (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Valutazione)
   * @return valutazione
  **/
  @ApiModelProperty(example = "null", value = "[Attributo aggiuntivo, previsto in ambiti regionali] Valutazione del responsabile dl programma (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=Valutazione)")
  public Long getValutazione() {
    return valutazione;
  }

  public void setValutazione(Long valutazione) {
    this.valutazione = valutazione;
  }

  public AcquistoEntry rup(DatiGeneraliTecnicoEntry rup) {
    this.rup = rup;
    return this;
  }

   /**
   * Responsabile unico RUP
   * @return rup
  **/
  @ApiModelProperty(example = "null", value = "Responsabile unico RUP")
  public DatiGeneraliTecnicoEntry getRup() {
    return rup;
  }

  public void setRup(DatiGeneraliTecnicoEntry rup) {
    this.rup = rup;
  }

  public AcquistoEntry importoCapitalePrivato(Double importoCapitalePrivato) {
    this.importoCapitalePrivato = importoCapitalePrivato;
    return this;
  }

   /**
   * Get importoCapitalePrivato
   * @return importoCapitalePrivato
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getImportoCapitalePrivato() {
    return importoCapitalePrivato;
  }

  public void setImportoCapitalePrivato(Double importoCapitalePrivato) {
    this.importoCapitalePrivato = importoCapitalePrivato;
  }

  public AcquistoEntry importoTotale(Double importoTotale) {
    this.importoTotale = importoTotale;
    return this;
  }

   /**
   * Get importoTotale
   * @return importoTotale
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getImportoTotale() {
    return importoTotale;
  }

  public void setImportoTotale(Double importoTotale) {
    this.importoTotale = importoTotale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcquistoEntry acquistoEntry = (AcquistoEntry) o;
    return Objects.equals(this.cui, acquistoEntry.cui) &&
        Objects.equals(this.settore, acquistoEntry.settore) &&
        Objects.equals(this.codiceInterno, acquistoEntry.codiceInterno) &&
        Objects.equals(this.descrizione, acquistoEntry.descrizione) &&
        Objects.equals(this.anno, acquistoEntry.anno) &&
        Objects.equals(this.esenteCup, acquistoEntry.esenteCup) &&
        Objects.equals(this.cup, acquistoEntry.cup) &&
        Objects.equals(this.acquistoRicompreso, acquistoEntry.acquistoRicompreso) &&
        Objects.equals(this.cuiCollegato, acquistoEntry.cuiCollegato) &&
        Objects.equals(this.cpv, acquistoEntry.cpv) &&
        Objects.equals(this.istat, acquistoEntry.istat) &&
        Objects.equals(this.nuts, acquistoEntry.nuts) &&
        Objects.equals(this.quantita, acquistoEntry.quantita) &&
        Objects.equals(this.unitaMisura, acquistoEntry.unitaMisura) &&
        Objects.equals(this.priorita, acquistoEntry.priorita) &&
        Objects.equals(this.lottoFunzionale, acquistoEntry.lottoFunzionale) &&
        Objects.equals(this.durataInMesi, acquistoEntry.durataInMesi) &&
        Objects.equals(this.nuovoAffidamento, acquistoEntry.nuovoAffidamento) &&
        Objects.equals(this.risorseVincolatePerLegge1, acquistoEntry.risorseVincolatePerLegge1) &&
        Objects.equals(this.risorseVincolatePerLegge2, acquistoEntry.risorseVincolatePerLegge2) &&
        Objects.equals(this.risorseVincolatePerLeggeSucc, acquistoEntry.risorseVincolatePerLeggeSucc) &&
        Objects.equals(this.risorseMutuo1, acquistoEntry.risorseMutuo1) &&
        Objects.equals(this.risorseMutuo2, acquistoEntry.risorseMutuo2) &&
        Objects.equals(this.risorseMutuoSucc, acquistoEntry.risorseMutuoSucc) &&
        Objects.equals(this.risorsePrivati1, acquistoEntry.risorsePrivati1) &&
        Objects.equals(this.risorsePrivati2, acquistoEntry.risorsePrivati2) &&
        Objects.equals(this.risorsePrivatiSucc, acquistoEntry.risorsePrivatiSucc) &&
        Objects.equals(this.risorseBilancio1, acquistoEntry.risorseBilancio1) &&
        Objects.equals(this.risorseBilancio2, acquistoEntry.risorseBilancio2) &&
        Objects.equals(this.risorseBilancioSucc, acquistoEntry.risorseBilancioSucc) &&
        Objects.equals(this.risorseArt31, acquistoEntry.risorseArt31) &&
        Objects.equals(this.risorseArt32, acquistoEntry.risorseArt32) &&
        Objects.equals(this.risorseArt3Succ, acquistoEntry.risorseArt3Succ) &&
        Objects.equals(this.risorseImmobili1, acquistoEntry.risorseImmobili1) &&
        Objects.equals(this.risorseImmobili2, acquistoEntry.risorseImmobili2) &&
        Objects.equals(this.risorseImmobiliSucc, acquistoEntry.risorseImmobiliSucc) &&
        Objects.equals(this.risorseAltro1, acquistoEntry.risorseAltro1) &&
        Objects.equals(this.risorseAltro2, acquistoEntry.risorseAltro2) &&
        Objects.equals(this.risorseAltroSucc, acquistoEntry.risorseAltroSucc) &&
        Objects.equals(this.speseSostenute, acquistoEntry.speseSostenute) &&
        Objects.equals(this.tipologiaCapitalePrivato, acquistoEntry.tipologiaCapitalePrivato) &&
        Objects.equals(this.importoRisorseFinanziarie, acquistoEntry.importoRisorseFinanziarie) &&
        Objects.equals(this.importoRisorseFinanziarieRegionali, acquistoEntry.importoRisorseFinanziarieRegionali) &&
        Objects.equals(this.importoRisorseFinanziarieAltro, acquistoEntry.importoRisorseFinanziarieAltro) &&
        Objects.equals(this.meseAvvioProcedura, acquistoEntry.meseAvvioProcedura) &&
        Objects.equals(this.delega, acquistoEntry.delega) &&
        Objects.equals(this.codiceSoggettoDelegato, acquistoEntry.codiceSoggettoDelegato) &&
        Objects.equals(this.nomeSoggettoDelegato, acquistoEntry.nomeSoggettoDelegato) &&
        Objects.equals(this.variato, acquistoEntry.variato) &&
        Objects.equals(this.note, acquistoEntry.note) &&
        Objects.equals(this.direzioneGenerale, acquistoEntry.direzioneGenerale) &&
        Objects.equals(this.strutturaOperativa, acquistoEntry.strutturaOperativa) &&
        Objects.equals(this.referenteDati, acquistoEntry.referenteDati) &&
        Objects.equals(this.dirigenteResponsabile, acquistoEntry.dirigenteResponsabile) &&
        Objects.equals(this.proceduraAffidamento, acquistoEntry.proceduraAffidamento) &&
        Objects.equals(this.acquistoVerdi, acquistoEntry.acquistoVerdi) &&
        Objects.equals(this.normativaRiferimento, acquistoEntry.normativaRiferimento) &&
        Objects.equals(this.oggettoVerdi, acquistoEntry.oggettoVerdi) &&
        Objects.equals(this.cpvVerdi, acquistoEntry.cpvVerdi) &&
        Objects.equals(this.importoNettoIvaVerdi, acquistoEntry.importoNettoIvaVerdi) &&
        Objects.equals(this.importoIvaVerdi, acquistoEntry.importoIvaVerdi) &&
        Objects.equals(this.importoTotVerdi, acquistoEntry.importoTotVerdi) &&
        Objects.equals(this.acquistoMaterialiRiciclati, acquistoEntry.acquistoMaterialiRiciclati) &&
        Objects.equals(this.oggettoMatRic, acquistoEntry.oggettoMatRic) &&
        Objects.equals(this.cpvMatRic, acquistoEntry.cpvMatRic) &&
        Objects.equals(this.importoNettoIvaMatRic, acquistoEntry.importoNettoIvaMatRic) &&
        Objects.equals(this.importoIvaMatRic, acquistoEntry.importoIvaMatRic) &&
        Objects.equals(this.importoTotMatRic, acquistoEntry.importoTotMatRic) &&
        Objects.equals(this.importoIva1, acquistoEntry.importoIva1) &&
        Objects.equals(this.importoIva2, acquistoEntry.importoIva2) &&
        Objects.equals(this.importoIvaSucc, acquistoEntry.importoIvaSucc) &&
        Objects.equals(this.coperturaFinanziaria, acquistoEntry.coperturaFinanziaria) &&
        Objects.equals(this.valutazione, acquistoEntry.valutazione) &&
        Objects.equals(this.rup, acquistoEntry.rup) &&
        Objects.equals(this.importoCapitalePrivato, acquistoEntry.importoCapitalePrivato) &&
        Objects.equals(this.importoTotale, acquistoEntry.importoTotale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cui, settore, codiceInterno, descrizione, anno, esenteCup, cup, acquistoRicompreso, cuiCollegato, cpv, istat, nuts, quantita, unitaMisura, priorita, lottoFunzionale, durataInMesi, nuovoAffidamento, risorseVincolatePerLegge1, risorseVincolatePerLegge2, risorseVincolatePerLeggeSucc, risorseMutuo1, risorseMutuo2, risorseMutuoSucc, risorsePrivati1, risorsePrivati2, risorsePrivatiSucc, risorseBilancio1, risorseBilancio2, risorseBilancioSucc, risorseArt31, risorseArt32, risorseArt3Succ, risorseImmobili1, risorseImmobili2, risorseImmobiliSucc, risorseAltro1, risorseAltro2, risorseAltroSucc, speseSostenute, tipologiaCapitalePrivato, importoRisorseFinanziarie, importoRisorseFinanziarieRegionali, importoRisorseFinanziarieAltro, meseAvvioProcedura, delega, codiceSoggettoDelegato, nomeSoggettoDelegato, variato, note, direzioneGenerale, strutturaOperativa, referenteDati, dirigenteResponsabile, proceduraAffidamento, acquistoVerdi, normativaRiferimento, oggettoVerdi, cpvVerdi, importoNettoIvaVerdi, importoIvaVerdi, importoTotVerdi, acquistoMaterialiRiciclati, oggettoMatRic, cpvMatRic, importoNettoIvaMatRic, importoIvaMatRic, importoTotMatRic, importoIva1, importoIva2, importoIvaSucc, coperturaFinanziaria, valutazione, rup, importoCapitalePrivato, importoTotale);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcquistoEntry {\n");
    
    sb.append("    cui: ").append(toIndentedString(cui)).append("\n");
    sb.append("    settore: ").append(toIndentedString(settore)).append("\n");
    sb.append("    codiceInterno: ").append(toIndentedString(codiceInterno)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    anno: ").append(toIndentedString(anno)).append("\n");
    sb.append("    esenteCup: ").append(toIndentedString(esenteCup)).append("\n");
    sb.append("    cup: ").append(toIndentedString(cup)).append("\n");
    sb.append("    acquistoRicompreso: ").append(toIndentedString(acquistoRicompreso)).append("\n");
    sb.append("    cuiCollegato: ").append(toIndentedString(cuiCollegato)).append("\n");
    sb.append("    cpv: ").append(toIndentedString(cpv)).append("\n");
    sb.append("    istat: ").append(toIndentedString(istat)).append("\n");
    sb.append("    nuts: ").append(toIndentedString(nuts)).append("\n");
    sb.append("    quantita: ").append(toIndentedString(quantita)).append("\n");
    sb.append("    unitaMisura: ").append(toIndentedString(unitaMisura)).append("\n");
    sb.append("    priorita: ").append(toIndentedString(priorita)).append("\n");
    sb.append("    lottoFunzionale: ").append(toIndentedString(lottoFunzionale)).append("\n");
    sb.append("    durataInMesi: ").append(toIndentedString(durataInMesi)).append("\n");
    sb.append("    nuovoAffidamento: ").append(toIndentedString(nuovoAffidamento)).append("\n");
    sb.append("    risorseVincolatePerLegge1: ").append(toIndentedString(risorseVincolatePerLegge1)).append("\n");
    sb.append("    risorseVincolatePerLegge2: ").append(toIndentedString(risorseVincolatePerLegge2)).append("\n");
    sb.append("    risorseVincolatePerLeggeSucc: ").append(toIndentedString(risorseVincolatePerLeggeSucc)).append("\n");
    sb.append("    risorseMutuo1: ").append(toIndentedString(risorseMutuo1)).append("\n");
    sb.append("    risorseMutuo2: ").append(toIndentedString(risorseMutuo2)).append("\n");
    sb.append("    risorseMutuoSucc: ").append(toIndentedString(risorseMutuoSucc)).append("\n");
    sb.append("    risorsePrivati1: ").append(toIndentedString(risorsePrivati1)).append("\n");
    sb.append("    risorsePrivati2: ").append(toIndentedString(risorsePrivati2)).append("\n");
    sb.append("    risorsePrivatiSucc: ").append(toIndentedString(risorsePrivatiSucc)).append("\n");
    sb.append("    risorseBilancio1: ").append(toIndentedString(risorseBilancio1)).append("\n");
    sb.append("    risorseBilancio2: ").append(toIndentedString(risorseBilancio2)).append("\n");
    sb.append("    risorseBilancioSucc: ").append(toIndentedString(risorseBilancioSucc)).append("\n");
    sb.append("    risorseArt31: ").append(toIndentedString(risorseArt31)).append("\n");
    sb.append("    risorseArt32: ").append(toIndentedString(risorseArt32)).append("\n");
    sb.append("    risorseArt3Succ: ").append(toIndentedString(risorseArt3Succ)).append("\n");
    sb.append("    risorseImmobili1: ").append(toIndentedString(risorseImmobili1)).append("\n");
    sb.append("    risorseImmobili2: ").append(toIndentedString(risorseImmobili2)).append("\n");
    sb.append("    risorseImmobiliSucc: ").append(toIndentedString(risorseImmobiliSucc)).append("\n");
    sb.append("    risorseAltro1: ").append(toIndentedString(risorseAltro1)).append("\n");
    sb.append("    risorseAltro2: ").append(toIndentedString(risorseAltro2)).append("\n");
    sb.append("    risorseAltroSucc: ").append(toIndentedString(risorseAltroSucc)).append("\n");
    sb.append("    speseSostenute: ").append(toIndentedString(speseSostenute)).append("\n");
    sb.append("    tipologiaCapitalePrivato: ").append(toIndentedString(tipologiaCapitalePrivato)).append("\n");
    sb.append("    importoRisorseFinanziarie: ").append(toIndentedString(importoRisorseFinanziarie)).append("\n");
    sb.append("    importoRisorseFinanziarieRegionali: ").append(toIndentedString(importoRisorseFinanziarieRegionali)).append("\n");
    sb.append("    importoRisorseFinanziarieAltro: ").append(toIndentedString(importoRisorseFinanziarieAltro)).append("\n");
    sb.append("    meseAvvioProcedura: ").append(toIndentedString(meseAvvioProcedura)).append("\n");
    sb.append("    delega: ").append(toIndentedString(delega)).append("\n");
    sb.append("    codiceSoggettoDelegato: ").append(toIndentedString(codiceSoggettoDelegato)).append("\n");
    sb.append("    nomeSoggettoDelegato: ").append(toIndentedString(nomeSoggettoDelegato)).append("\n");
    sb.append("    variato: ").append(toIndentedString(variato)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    direzioneGenerale: ").append(toIndentedString(direzioneGenerale)).append("\n");
    sb.append("    strutturaOperativa: ").append(toIndentedString(strutturaOperativa)).append("\n");
    sb.append("    referenteDati: ").append(toIndentedString(referenteDati)).append("\n");
    sb.append("    dirigenteResponsabile: ").append(toIndentedString(dirigenteResponsabile)).append("\n");
    sb.append("    proceduraAffidamento: ").append(toIndentedString(proceduraAffidamento)).append("\n");
    sb.append("    acquistoVerdi: ").append(toIndentedString(acquistoVerdi)).append("\n");
    sb.append("    normativaRiferimento: ").append(toIndentedString(normativaRiferimento)).append("\n");
    sb.append("    oggettoVerdi: ").append(toIndentedString(oggettoVerdi)).append("\n");
    sb.append("    cpvVerdi: ").append(toIndentedString(cpvVerdi)).append("\n");
    sb.append("    importoNettoIvaVerdi: ").append(toIndentedString(importoNettoIvaVerdi)).append("\n");
    sb.append("    importoIvaVerdi: ").append(toIndentedString(importoIvaVerdi)).append("\n");
    sb.append("    importoTotVerdi: ").append(toIndentedString(importoTotVerdi)).append("\n");
    sb.append("    acquistoMaterialiRiciclati: ").append(toIndentedString(acquistoMaterialiRiciclati)).append("\n");
    sb.append("    oggettoMatRic: ").append(toIndentedString(oggettoMatRic)).append("\n");
    sb.append("    cpvMatRic: ").append(toIndentedString(cpvMatRic)).append("\n");
    sb.append("    importoNettoIvaMatRic: ").append(toIndentedString(importoNettoIvaMatRic)).append("\n");
    sb.append("    importoIvaMatRic: ").append(toIndentedString(importoIvaMatRic)).append("\n");
    sb.append("    importoTotMatRic: ").append(toIndentedString(importoTotMatRic)).append("\n");
    sb.append("    importoIva1: ").append(toIndentedString(importoIva1)).append("\n");
    sb.append("    importoIva2: ").append(toIndentedString(importoIva2)).append("\n");
    sb.append("    importoIvaSucc: ").append(toIndentedString(importoIvaSucc)).append("\n");
    sb.append("    coperturaFinanziaria: ").append(toIndentedString(coperturaFinanziaria)).append("\n");
    sb.append("    valutazione: ").append(toIndentedString(valutazione)).append("\n");
    sb.append("    rup: ").append(toIndentedString(rup)).append("\n");
    sb.append("    importoCapitalePrivato: ").append(toIndentedString(importoCapitalePrivato)).append("\n");
    sb.append("    importoTotale: ").append(toIndentedString(importoTotale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

