/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2020 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.csi.cpass.cpassbe.mit.client.model.programmi.PubblicaProgrammaLavoriEntry;


/**
 * Contenitore per il risultato del dettaglio di un programma lavori
 */
@ApiModel(description = "Contenitore per il risultato del dettaglio di un programma lavori")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class DettaglioLavoriResult   {
  @SerializedName("error")
  private String error = null;

  @SerializedName("programma")
  private PubblicaProgrammaLavoriEntry programma = null;

  public DettaglioLavoriResult error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Eventuale messaggio di errore in caso di operazione fallita
   * @return error
  **/
  @ApiModelProperty(example = "null", value = "Eventuale messaggio di errore in caso di operazione fallita")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public DettaglioLavoriResult programma(PubblicaProgrammaLavoriEntry programma) {
    this.programma = programma;
    return this;
  }

   /**
   * Dettaglio del programma lavori
   * @return programma
  **/
  @ApiModelProperty(example = "null", value = "Dettaglio del programma lavori")
  public PubblicaProgrammaLavoriEntry getProgramma() {
    return programma;
  }

  public void setProgramma(PubblicaProgrammaLavoriEntry programma) {
    this.programma = programma;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DettaglioLavoriResult dettaglioLavoriResult = (DettaglioLavoriResult) o;
    return Objects.equals(this.error, dettaglioLavoriResult.error) &&
        Objects.equals(this.programma, dettaglioLavoriResult.programma);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, programma);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DettaglioLavoriResult {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    programma: ").append(toIndentedString(programma)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

