/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2020 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contenitore per dati di un&#39;immobile
 */
@ApiModel(description = "Contenitore per dati di un'immobile")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class ImmobileEntry   {
  @SerializedName("cui")
  private String cui = null;

  @SerializedName("istat")
  private String istat = null;

  @SerializedName("nuts")
  private String nuts = null;

  @SerializedName("trasferimentoTitoloCorrispettivo")
  private Long trasferimentoTitoloCorrispettivo = null;

  @SerializedName("immobileDisponibile")
  private Long immobileDisponibile = null;

  @SerializedName("alienati")
  private String alienati = null;

  @SerializedName("inclusoProgrammaDismissione")
  private Long inclusoProgrammaDismissione = null;

  @SerializedName("descrizione")
  private String descrizione = null;

  @SerializedName("tipoDisponibilita")
  private Long tipoDisponibilita = null;

  @SerializedName("valoreStimato1")
  private Double valoreStimato1 = null;

  @SerializedName("valoreStimato2")
  private Double valoreStimato2 = null;

  @SerializedName("valoreStimato3")
  private Double valoreStimato3 = null;

  @SerializedName("valoreStimatoSucc")
  private Double valoreStimatoSucc = null;

  public ImmobileEntry cui(String cui) {
    this.cui = cui;
    return this;
  }

   /**
   * Codice univoco immobile (�I� + CodiceFiscale Stazione Appaltante(11 char) + anno (4 char) + progressivo (5 char))
   * @return cui
  **/
  @ApiModelProperty(example = "null", required = true, value = "Codice univoco immobile (�I� + CodiceFiscale Stazione Appaltante(11 char) + anno (4 char) + progressivo (5 char))")
  public String getCui() {
    return cui;
  }

  public void setCui(String cui) {
    this.cui = cui;
  }

  public ImmobileEntry istat(String istat) {
    this.istat = istat;
    return this;
  }

   /**
   * Localizzazione - Codice ISTAT del Comune
   * @return istat
  **/
  @ApiModelProperty(example = "null", value = "Localizzazione - Codice ISTAT del Comune")
  public String getIstat() {
    return istat;
  }

  public void setIstat(String istat) {
    this.istat = istat;
  }

  public ImmobileEntry nuts(String nuts) {
    this.nuts = nuts;
    return this;
  }

   /**
   * Localizzazione - NUTS
   * @return nuts
  **/
  @ApiModelProperty(example = "null", value = "Localizzazione - NUTS")
  public String getNuts() {
    return nuts;
  }

  public void setNuts(String nuts) {
    this.nuts = nuts;
  }

  public ImmobileEntry trasferimentoTitoloCorrispettivo(Long trasferimentoTitoloCorrispettivo) {
    this.trasferimentoTitoloCorrispettivo = trasferimentoTitoloCorrispettivo;
    return this;
  }

   /**
   * Trasferimento immobile a titolo corrispettivo (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=TrasferimentoImmobile)
   * @return trasferimentoTitoloCorrispettivo
  **/
  @ApiModelProperty(example = "null", value = "Trasferimento immobile a titolo corrispettivo (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=TrasferimentoImmobile)")
  public Long getTrasferimentoTitoloCorrispettivo() {
    return trasferimentoTitoloCorrispettivo;
  }

  public void setTrasferimentoTitoloCorrispettivo(Long trasferimentoTitoloCorrispettivo) {
    this.trasferimentoTitoloCorrispettivo = trasferimentoTitoloCorrispettivo;
  }

  public ImmobileEntry immobileDisponibile(Long immobileDisponibile) {
    this.immobileDisponibile = immobileDisponibile;
    return this;
  }

   /**
   * Immobile disponibile art. 21-c5 (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=ImmobileDisponibile)
   * @return immobileDisponibile
  **/
  @ApiModelProperty(example = "null", value = "Immobile disponibile art. 21-c5 (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=ImmobileDisponibile)")
  public Long getImmobileDisponibile() {
    return immobileDisponibile;
  }

  public void setImmobileDisponibile(Long immobileDisponibile) {
    this.immobileDisponibile = immobileDisponibile;
  }

  public ImmobileEntry alienati(String alienati) {
    this.alienati = alienati;
    return this;
  }

   /**
   * [Attributo non utilizzato] Alienati per il finanziamento e la realizzazione di opere pubbliche (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)
   * @return alienati
  **/
  @ApiModelProperty(example = "null", value = "[Attributo non utilizzato] Alienati per il finanziamento e la realizzazione di opere pubbliche (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=SN)")
  public String getAlienati() {
    return alienati;
  }

  public void setAlienati(String alienati) {
    this.alienati = alienati;
  }

  public ImmobileEntry inclusoProgrammaDismissione(Long inclusoProgrammaDismissione) {
    this.inclusoProgrammaDismissione = inclusoProgrammaDismissione;
    return this;
  }

   /**
   * Gi� incluso in programma di dismissione art. 27 DL 201/2011 (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=ProgrammaDismissione)
   * @return inclusoProgrammaDismissione
  **/
  @ApiModelProperty(example = "null", value = "Gi� incluso in programma di dismissione art. 27 DL 201/2011 (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=ProgrammaDismissione)")
  public Long getInclusoProgrammaDismissione() {
    return inclusoProgrammaDismissione;
  }

  public void setInclusoProgrammaDismissione(Long inclusoProgrammaDismissione) {
    this.inclusoProgrammaDismissione = inclusoProgrammaDismissione;
  }

  public ImmobileEntry descrizione(String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Descrizione dell'immobile
   * @return descrizione
  **/
  @ApiModelProperty(example = "null", value = "Descrizione dell'immobile")
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(String descrizione) {
    this.descrizione = descrizione;
  }

  public ImmobileEntry tipoDisponibilita(Long tipoDisponibilita) {
    this.tipoDisponibilita = tipoDisponibilita;
    return this;
  }

   /**
   * Tipo propriet� (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=TipoDisponibilita)
   * @return tipoDisponibilita
  **/
  @ApiModelProperty(example = "null", value = "Tipo propriet� (/WSTabelleDiContesto/rest/Tabellati/Valori?cod=TipoDisponibilita)")
  public Long getTipoDisponibilita() {
    return tipoDisponibilita;
  }

  public void setTipoDisponibilita(Long tipoDisponibilita) {
    this.tipoDisponibilita = tipoDisponibilita;
  }

  public ImmobileEntry valoreStimato1(Double valoreStimato1) {
    this.valoreStimato1 = valoreStimato1;
    return this;
  }

   /**
   * Valore stimato dell'immobile - Primo anno
   * @return valoreStimato1
  **/
  @ApiModelProperty(example = "null", value = "Valore stimato dell'immobile - Primo anno")
  public Double getValoreStimato1() {
    return valoreStimato1;
  }

  public void setValoreStimato1(Double valoreStimato1) {
    this.valoreStimato1 = valoreStimato1;
  }

  public ImmobileEntry valoreStimato2(Double valoreStimato2) {
    this.valoreStimato2 = valoreStimato2;
    return this;
  }

   /**
   * Valore stimato dell'immobile - Secondo anno
   * @return valoreStimato2
  **/
  @ApiModelProperty(example = "null", value = "Valore stimato dell'immobile - Secondo anno")
  public Double getValoreStimato2() {
    return valoreStimato2;
  }

  public void setValoreStimato2(Double valoreStimato2) {
    this.valoreStimato2 = valoreStimato2;
  }

  public ImmobileEntry valoreStimato3(Double valoreStimato3) {
    this.valoreStimato3 = valoreStimato3;
    return this;
  }

   /**
   * Valore stimato dell'immobile - Terzo anno
   * @return valoreStimato3
  **/
  @ApiModelProperty(example = "null", value = "Valore stimato dell'immobile - Terzo anno")
  public Double getValoreStimato3() {
    return valoreStimato3;
  }

  public void setValoreStimato3(Double valoreStimato3) {
    this.valoreStimato3 = valoreStimato3;
  }

  public ImmobileEntry valoreStimatoSucc(Double valoreStimatoSucc) {
    this.valoreStimatoSucc = valoreStimatoSucc;
    return this;
  }

   /**
   * Valore stimato dell'immobile - Annualit� successive
   * @return valoreStimatoSucc
  **/
  @ApiModelProperty(example = "null", value = "Valore stimato dell'immobile - Annualit� successive")
  public Double getValoreStimatoSucc() {
    return valoreStimatoSucc;
  }

  public void setValoreStimatoSucc(Double valoreStimatoSucc) {
    this.valoreStimatoSucc = valoreStimatoSucc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImmobileEntry immobileEntry = (ImmobileEntry) o;
    return Objects.equals(this.cui, immobileEntry.cui) &&
        Objects.equals(this.istat, immobileEntry.istat) &&
        Objects.equals(this.nuts, immobileEntry.nuts) &&
        Objects.equals(this.trasferimentoTitoloCorrispettivo, immobileEntry.trasferimentoTitoloCorrispettivo) &&
        Objects.equals(this.immobileDisponibile, immobileEntry.immobileDisponibile) &&
        Objects.equals(this.alienati, immobileEntry.alienati) &&
        Objects.equals(this.inclusoProgrammaDismissione, immobileEntry.inclusoProgrammaDismissione) &&
        Objects.equals(this.descrizione, immobileEntry.descrizione) &&
        Objects.equals(this.tipoDisponibilita, immobileEntry.tipoDisponibilita) &&
        Objects.equals(this.valoreStimato1, immobileEntry.valoreStimato1) &&
        Objects.equals(this.valoreStimato2, immobileEntry.valoreStimato2) &&
        Objects.equals(this.valoreStimato3, immobileEntry.valoreStimato3) &&
        Objects.equals(this.valoreStimatoSucc, immobileEntry.valoreStimatoSucc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cui, istat, nuts, trasferimentoTitoloCorrispettivo, immobileDisponibile, alienati, inclusoProgrammaDismissione, descrizione, tipoDisponibilita, valoreStimato1, valoreStimato2, valoreStimato3, valoreStimatoSucc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImmobileEntry {\n");
    
    sb.append("    cui: ").append(toIndentedString(cui)).append("\n");
    sb.append("    istat: ").append(toIndentedString(istat)).append("\n");
    sb.append("    nuts: ").append(toIndentedString(nuts)).append("\n");
    sb.append("    trasferimentoTitoloCorrispettivo: ").append(toIndentedString(trasferimentoTitoloCorrispettivo)).append("\n");
    sb.append("    immobileDisponibile: ").append(toIndentedString(immobileDisponibile)).append("\n");
    sb.append("    alienati: ").append(toIndentedString(alienati)).append("\n");
    sb.append("    inclusoProgrammaDismissione: ").append(toIndentedString(inclusoProgrammaDismissione)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    tipoDisponibilita: ").append(toIndentedString(tipoDisponibilita)).append("\n");
    sb.append("    valoreStimato1: ").append(toIndentedString(valoreStimato1)).append("\n");
    sb.append("    valoreStimato2: ").append(toIndentedString(valoreStimato2)).append("\n");
    sb.append("    valoreStimato3: ").append(toIndentedString(valoreStimato3)).append("\n");
    sb.append("    valoreStimatoSucc: ").append(toIndentedString(valoreStimatoSucc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

