/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2025 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contenitore per dati di un lavoro in ecomomia
 */
@ApiModel(description = "Contenitore per dati di un lavoro in ecomomia")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class LavoroEconomiaEntry   {
	@SerializedName("descrizione")
	private String descrizione = null;

	@SerializedName("cup")
	private String cup = null;

	@SerializedName("stimaLavori")
	private Double stimaLavori = null;

	public LavoroEconomiaEntry descrizione(String descrizione) {
		this.descrizione = descrizione;
		return this;
	}

	/**
	 * Descrizione
	 * @return descrizione
	 **/
	@ApiModelProperty(example = "null", value = "Descrizione")
	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public LavoroEconomiaEntry cup(String cup) {
		this.cup = cup;
		return this;
	}

	/**
	 * Codice CUP
	 * @return cup
	 **/
	@ApiModelProperty(example = "null", value = "Codice CUP")
	public String getCup() {
		return cup;
	}

	public void setCup(String cup) {
		this.cup = cup;
	}

	public LavoroEconomiaEntry stimaLavori(Double stimaLavori) {
		this.stimaLavori = stimaLavori;
		return this;
	}

	/**
	 * Stima lavori
	 * @return stimaLavori
	 **/
	@ApiModelProperty(example = "null", value = "Stima lavori")
	public Double getStimaLavori() {
		return stimaLavori;
	}

	public void setStimaLavori(Double stimaLavori) {
		this.stimaLavori = stimaLavori;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		final LavoroEconomiaEntry lavoroEconomiaEntry = (LavoroEconomiaEntry) o;
		return Objects.equals(this.descrizione, lavoroEconomiaEntry.descrizione) &&
				Objects.equals(this.cup, lavoroEconomiaEntry.cup) &&
				Objects.equals(this.stimaLavori, lavoroEconomiaEntry.stimaLavori);
	}

	@Override
	public int hashCode() {
		return Objects.hash(descrizione, cup, stimaLavori);
	}

	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder();
		sb.append("class LavoroEconomiaEntry {\n");

		sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
		sb.append("    cup: ").append(toIndentedString(cup)).append("\n");
		sb.append("    stimaLavori: ").append(toIndentedString(stimaLavori)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}

