/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2020 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.csi.cpass.cpassbe.mit.client.model.programmi.AcquistoEntry;
import it.csi.cpass.cpassbe.mit.client.model.programmi.AcquistoNonRipropostoEntry;
import it.csi.cpass.cpassbe.mit.client.model.programmi.DatiGeneraliTecnicoEntry;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * Contenitore per i dati di pubblicazione di un programma di forniture e servizi
 */
@ApiModel(description = "Contenitore per i dati di pubblicazione di un programma di forniture e servizi")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class PubblicaProgrammaFornitureServiziEntry   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("codiceFiscaleSA")
  private String codiceFiscaleSA = null;

  @SerializedName("ufficio")
  private String ufficio = null;

  @SerializedName("anno")
  private Long anno = null;

  @SerializedName("descrizione")
  private String descrizione = null;

  @SerializedName("numeroApprovazione")
  private String numeroApprovazione = null;

  @SerializedName("dataApprovazione")
  private DateTime dataApprovazione = null;

  @SerializedName("dataPubblicazioneApprovazione")
  private DateTime dataPubblicazioneApprovazione = null;

  @SerializedName("titoloAttoApprovazione")
  private String titoloAttoApprovazione = null;

  @SerializedName("urlAttoApprovazione")
  private String urlAttoApprovazione = null;

  @SerializedName("primaPubblicazioneSCP")
  private DateTime primaPubblicazioneSCP = null;

  @SerializedName("ultimaModificaSCP")
  private DateTime ultimaModificaSCP = null;

  @SerializedName("referente")
  private DatiGeneraliTecnicoEntry referente = null;

  @SerializedName("acquisti")
  private List<AcquistoEntry> acquisti = new ArrayList<AcquistoEntry>();

  @SerializedName("acquistiNonRiproposti")
  private List<AcquistoNonRipropostoEntry> acquistiNonRiproposti = new ArrayList<AcquistoNonRipropostoEntry>();

  @SerializedName("idRicevuto")
  private Long idRicevuto = null;

  public PubblicaProgrammaFornitureServiziEntry id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID del programma ('FS' + CodiceFiscaleSA(11 caratteri) + anno(4 cifre) + progressivo(3 cifre))
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "ID del programma ('FS' + CodiceFiscaleSA(11 caratteri) + anno(4 cifre) + progressivo(3 cifre))")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PubblicaProgrammaFornitureServiziEntry codiceFiscaleSA(String codiceFiscaleSA) {
    this.codiceFiscaleSA = codiceFiscaleSA;
    return this;
  }

   /**
   * Codice Fiscale Stazione appaltante
   * @return codiceFiscaleSA
  **/
  @ApiModelProperty(example = "null", required = true, value = "Codice Fiscale Stazione appaltante")
  public String getCodiceFiscaleSA() {
    return codiceFiscaleSA;
  }

  public void setCodiceFiscaleSA(String codiceFiscaleSA) {
    this.codiceFiscaleSA = codiceFiscaleSA;
  }

  public PubblicaProgrammaFornitureServiziEntry ufficio(String ufficio) {
    this.ufficio = ufficio;
    return this;
  }

   /**
   * Ufficio/area di pertinenza
   * @return ufficio
  **/
  @ApiModelProperty(example = "null", value = "Ufficio/area di pertinenza")
  public String getUfficio() {
    return ufficio;
  }

  public void setUfficio(String ufficio) {
    this.ufficio = ufficio;
  }

  public PubblicaProgrammaFornitureServiziEntry anno(Long anno) {
    this.anno = anno;
    return this;
  }

   /**
   * Anno di inizio del programma
   * @return anno
  **/
  @ApiModelProperty(example = "null", required = true, value = "Anno di inizio del programma")
  public Long getAnno() {
    return anno;
  }

  public void setAnno(Long anno) {
    this.anno = anno;
  }

  public PubblicaProgrammaFornitureServiziEntry descrizione(String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Descrizione del Programma
   * @return descrizione
  **/
  @ApiModelProperty(example = "null", required = true, value = "Descrizione del Programma")
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(String descrizione) {
    this.descrizione = descrizione;
  }

  public PubblicaProgrammaFornitureServiziEntry numeroApprovazione(String numeroApprovazione) {
    this.numeroApprovazione = numeroApprovazione;
    return this;
  }

   /**
   * Numero approvazione
   * @return numeroApprovazione
  **/
  @ApiModelProperty(example = "null", value = "Numero approvazione")
  public String getNumeroApprovazione() {
    return numeroApprovazione;
  }

  public void setNumeroApprovazione(String numeroApprovazione) {
    this.numeroApprovazione = numeroApprovazione;
  }

  public PubblicaProgrammaFornitureServiziEntry dataApprovazione(DateTime dataApprovazione) {
    this.dataApprovazione = dataApprovazione;
    return this;
  }

   /**
   * Data approvazione
   * @return dataApprovazione
  **/
  @ApiModelProperty(example = "null", value = "Data approvazione")
  public DateTime getDataApprovazione() {
    return dataApprovazione;
  }

  public void setDataApprovazione(DateTime dataApprovazione) {
    this.dataApprovazione = dataApprovazione;
  }

  public PubblicaProgrammaFornitureServiziEntry dataPubblicazioneApprovazione(DateTime dataPubblicazioneApprovazione) {
    this.dataPubblicazioneApprovazione = dataPubblicazioneApprovazione;
    return this;
  }

   /**
   * Data pubblicazione approvazione
   * @return dataPubblicazioneApprovazione
  **/
  @ApiModelProperty(example = "null", value = "Data pubblicazione approvazione")
  public DateTime getDataPubblicazioneApprovazione() {
    return dataPubblicazioneApprovazione;
  }

  public void setDataPubblicazioneApprovazione(DateTime dataPubblicazioneApprovazione) {
    this.dataPubblicazioneApprovazione = dataPubblicazioneApprovazione;
  }

  public PubblicaProgrammaFornitureServiziEntry titoloAttoApprovazione(String titoloAttoApprovazione) {
    this.titoloAttoApprovazione = titoloAttoApprovazione;
    return this;
  }

   /**
   * Titolo atto approvazione
   * @return titoloAttoApprovazione
  **/
  @ApiModelProperty(example = "null", value = "Titolo atto approvazione")
  public String getTitoloAttoApprovazione() {
    return titoloAttoApprovazione;
  }

  public void setTitoloAttoApprovazione(String titoloAttoApprovazione) {
    this.titoloAttoApprovazione = titoloAttoApprovazione;
  }

  public PubblicaProgrammaFornitureServiziEntry urlAttoApprovazione(String urlAttoApprovazione) {
    this.urlAttoApprovazione = urlAttoApprovazione;
    return this;
  }

   /**
   * Url atto di approvazione
   * @return urlAttoApprovazione
  **/
  @ApiModelProperty(example = "null", value = "Url atto di approvazione")
  public String getUrlAttoApprovazione() {
    return urlAttoApprovazione;
  }

  public void setUrlAttoApprovazione(String urlAttoApprovazione) {
    this.urlAttoApprovazione = urlAttoApprovazione;
  }

  public PubblicaProgrammaFornitureServiziEntry primaPubblicazioneSCP(DateTime primaPubblicazioneSCP) {
    this.primaPubblicazioneSCP = primaPubblicazioneSCP;
    return this;
  }

   /**
   * Data pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioFornitureServizi)
   * @return primaPubblicazioneSCP
  **/
  @ApiModelProperty(example = "null", value = "Data pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioFornitureServizi)")
  public DateTime getPrimaPubblicazioneSCP() {
    return primaPubblicazioneSCP;
  }

  public void setPrimaPubblicazioneSCP(DateTime primaPubblicazioneSCP) {
    this.primaPubblicazioneSCP = primaPubblicazioneSCP;
  }

  public PubblicaProgrammaFornitureServiziEntry ultimaModificaSCP(DateTime ultimaModificaSCP) {
    this.ultimaModificaSCP = ultimaModificaSCP;
    return this;
  }

   /**
   * Utima modifica pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioFornitureServizi)
   * @return ultimaModificaSCP
  **/
  @ApiModelProperty(example = "null", value = "Utima modifica pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioFornitureServizi)")
  public DateTime getUltimaModificaSCP() {
    return ultimaModificaSCP;
  }

  public void setUltimaModificaSCP(DateTime ultimaModificaSCP) {
    this.ultimaModificaSCP = ultimaModificaSCP;
  }

  public PubblicaProgrammaFornitureServiziEntry referente(DatiGeneraliTecnicoEntry referente) {
    this.referente = referente;
    return this;
  }

   /**
   * Referente del programma
   * @return referente
  **/
  @ApiModelProperty(example = "null", required = true, value = "Referente del programma")
  public DatiGeneraliTecnicoEntry getReferente() {
    return referente;
  }

  public void setReferente(DatiGeneraliTecnicoEntry referente) {
    this.referente = referente;
  }

  public PubblicaProgrammaFornitureServiziEntry acquisti(List<AcquistoEntry> acquisti) {
    this.acquisti = acquisti;
    return this;
  }

  public PubblicaProgrammaFornitureServiziEntry addAcquistiItem(AcquistoEntry acquistiItem) {
    this.acquisti.add(acquistiItem);
    return this;
  }

   /**
   * Lista acquisti
   * @return acquisti
  **/
  @ApiModelProperty(example = "null", value = "Lista acquisti")
  public List<AcquistoEntry> getAcquisti() {
    return acquisti;
  }

  public void setAcquisti(List<AcquistoEntry> acquisti) {
    this.acquisti = acquisti;
  }

  public PubblicaProgrammaFornitureServiziEntry acquistiNonRiproposti(List<AcquistoNonRipropostoEntry> acquistiNonRiproposti) {
    this.acquistiNonRiproposti = acquistiNonRiproposti;
    return this;
  }

  public PubblicaProgrammaFornitureServiziEntry addAcquistiNonRipropostiItem(AcquistoNonRipropostoEntry acquistiNonRipropostiItem) {
    this.acquistiNonRiproposti.add(acquistiNonRipropostiItem);
    return this;
  }

   /**
   * Lista acquisti non riproposti
   * @return acquistiNonRiproposti
  **/
  @ApiModelProperty(example = "null", value = "Lista acquisti non riproposti")
  public List<AcquistoNonRipropostoEntry> getAcquistiNonRiproposti() {
    return acquistiNonRiproposti;
  }

  public void setAcquistiNonRiproposti(List<AcquistoNonRipropostoEntry> acquistiNonRiproposti) {
    this.acquistiNonRiproposti = acquistiNonRiproposti;
  }

  public PubblicaProgrammaFornitureServiziEntry idRicevuto(Long idRicevuto) {
    this.idRicevuto = idRicevuto;
    return this;
  }

   /**
   * Id univoco generato dal sistema remoto; deve essere utilizzato per le chiamate successive
   * @return idRicevuto
  **/
  @ApiModelProperty(example = "null", value = "Id univoco generato dal sistema remoto; deve essere utilizzato per le chiamate successive")
  public Long getIdRicevuto() {
    return idRicevuto;
  }

  public void setIdRicevuto(Long idRicevuto) {
    this.idRicevuto = idRicevuto;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PubblicaProgrammaFornitureServiziEntry pubblicaProgrammaFornitureServiziEntry = (PubblicaProgrammaFornitureServiziEntry) o;
    return Objects.equals(this.id, pubblicaProgrammaFornitureServiziEntry.id) &&
        Objects.equals(this.codiceFiscaleSA, pubblicaProgrammaFornitureServiziEntry.codiceFiscaleSA) &&
        Objects.equals(this.ufficio, pubblicaProgrammaFornitureServiziEntry.ufficio) &&
        Objects.equals(this.anno, pubblicaProgrammaFornitureServiziEntry.anno) &&
        Objects.equals(this.descrizione, pubblicaProgrammaFornitureServiziEntry.descrizione) &&
        Objects.equals(this.numeroApprovazione, pubblicaProgrammaFornitureServiziEntry.numeroApprovazione) &&
        Objects.equals(this.dataApprovazione, pubblicaProgrammaFornitureServiziEntry.dataApprovazione) &&
        Objects.equals(this.dataPubblicazioneApprovazione, pubblicaProgrammaFornitureServiziEntry.dataPubblicazioneApprovazione) &&
        Objects.equals(this.titoloAttoApprovazione, pubblicaProgrammaFornitureServiziEntry.titoloAttoApprovazione) &&
        Objects.equals(this.urlAttoApprovazione, pubblicaProgrammaFornitureServiziEntry.urlAttoApprovazione) &&
        Objects.equals(this.primaPubblicazioneSCP, pubblicaProgrammaFornitureServiziEntry.primaPubblicazioneSCP) &&
        Objects.equals(this.ultimaModificaSCP, pubblicaProgrammaFornitureServiziEntry.ultimaModificaSCP) &&
        Objects.equals(this.referente, pubblicaProgrammaFornitureServiziEntry.referente) &&
        Objects.equals(this.acquisti, pubblicaProgrammaFornitureServiziEntry.acquisti) &&
        Objects.equals(this.acquistiNonRiproposti, pubblicaProgrammaFornitureServiziEntry.acquistiNonRiproposti) &&
        Objects.equals(this.idRicevuto, pubblicaProgrammaFornitureServiziEntry.idRicevuto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, codiceFiscaleSA, ufficio, anno, descrizione, numeroApprovazione, dataApprovazione, dataPubblicazioneApprovazione, titoloAttoApprovazione, urlAttoApprovazione, primaPubblicazioneSCP, ultimaModificaSCP, referente, acquisti, acquistiNonRiproposti, idRicevuto);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PubblicaProgrammaFornitureServiziEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codiceFiscaleSA: ").append(toIndentedString(codiceFiscaleSA)).append("\n");
    sb.append("    ufficio: ").append(toIndentedString(ufficio)).append("\n");
    sb.append("    anno: ").append(toIndentedString(anno)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    numeroApprovazione: ").append(toIndentedString(numeroApprovazione)).append("\n");
    sb.append("    dataApprovazione: ").append(toIndentedString(dataApprovazione)).append("\n");
    sb.append("    dataPubblicazioneApprovazione: ").append(toIndentedString(dataPubblicazioneApprovazione)).append("\n");
    sb.append("    titoloAttoApprovazione: ").append(toIndentedString(titoloAttoApprovazione)).append("\n");
    sb.append("    urlAttoApprovazione: ").append(toIndentedString(urlAttoApprovazione)).append("\n");
    sb.append("    primaPubblicazioneSCP: ").append(toIndentedString(primaPubblicazioneSCP)).append("\n");
    sb.append("    ultimaModificaSCP: ").append(toIndentedString(ultimaModificaSCP)).append("\n");
    sb.append("    referente: ").append(toIndentedString(referente)).append("\n");
    sb.append("    acquisti: ").append(toIndentedString(acquisti)).append("\n");
    sb.append("    acquistiNonRiproposti: ").append(toIndentedString(acquistiNonRiproposti)).append("\n");
    sb.append("    idRicevuto: ").append(toIndentedString(idRicevuto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

