/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2025 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.joda.time.DateTime;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contenitore per i dati di pubblicazione di un programma per lavori
 */
@ApiModel(description = "Contenitore per i dati di pubblicazione di un programma per lavori")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class PubblicaProgrammaLavoriEntry   {
	@SerializedName("id")
	private String id = null;

	@SerializedName("codiceFiscaleSA")
	private String codiceFiscaleSA = null;

	@SerializedName("ufficio")
	private String ufficio = null;

	@SerializedName("anno")
	private Long anno = null;

	@SerializedName("descrizione")
	private String descrizione = null;

	@SerializedName("numeroApprovazione")
	private String numeroApprovazione = null;

	@SerializedName("dataApprovazione")
	private DateTime dataApprovazione = null;

	@SerializedName("dataPubblicazioneApprovazione")
	private DateTime dataPubblicazioneApprovazione = null;

	@SerializedName("titoloAttoApprovazione")
	private String titoloAttoApprovazione = null;

	@SerializedName("urlAttoApprovazione")
	private String urlAttoApprovazione = null;

	@SerializedName("numeroAdozione")
	private String numeroAdozione = null;

	@SerializedName("dataAdozione")
	private DateTime dataAdozione = null;

	@SerializedName("dataPubblicazioneAdozione")
	private DateTime dataPubblicazioneAdozione = null;

	@SerializedName("titoloAttoAdozione")
	private String titoloAttoAdozione = null;

	@SerializedName("urlAttoAdozione")
	private String urlAttoAdozione = null;

	@SerializedName("primaPubblicazioneSCP")
	private DateTime primaPubblicazioneSCP = null;

	@SerializedName("ultimaModificaSCP")
	private DateTime ultimaModificaSCP = null;

	@SerializedName("referente")
	private DatiGeneraliTecnicoEntry referente = null;

	@SerializedName("opereIncompiute")
	private List<OperaIncompiutaEntry> opereIncompiute = new ArrayList<>();

	@SerializedName("interventi")
	private List<InterventoEntry> interventi = new ArrayList<>();

	@SerializedName("interventiNonRiproposti")
	private List<InterventoNonRipropostoEntry> interventiNonRiproposti = new ArrayList<>();

	@SerializedName("idRicevuto")
	private Long idRicevuto = null;

	public PubblicaProgrammaLavoriEntry id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * ID del programma('LP' + CodiceFiscaleSA(11 caratteri) + anno(4 cifre) + progressivo(3 cifre))
	 * @return id
	 **/
	@ApiModelProperty(example = "null", required = true, value = "ID del programma('LP' + CodiceFiscaleSA(11 caratteri) + anno(4 cifre) + progressivo(3 cifre))")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PubblicaProgrammaLavoriEntry codiceFiscaleSA(String codiceFiscaleSA) {
		this.codiceFiscaleSA = codiceFiscaleSA;
		return this;
	}

	/**
	 * Codice Fiscale Stazione appaltante
	 * @return codiceFiscaleSA
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Codice Fiscale Stazione appaltante")
	public String getCodiceFiscaleSA() {
		return codiceFiscaleSA;
	}

	public void setCodiceFiscaleSA(String codiceFiscaleSA) {
		this.codiceFiscaleSA = codiceFiscaleSA;
	}

	public PubblicaProgrammaLavoriEntry ufficio(String ufficio) {
		this.ufficio = ufficio;
		return this;
	}

	/**
	 * Ufficio/area di pertinenza
	 * @return ufficio
	 **/
	@ApiModelProperty(example = "null", value = "Ufficio/area di pertinenza")
	public String getUfficio() {
		return ufficio;
	}

	public void setUfficio(String ufficio) {
		this.ufficio = ufficio;
	}

	public PubblicaProgrammaLavoriEntry anno(Long anno) {
		this.anno = anno;
		return this;
	}

	/**
	 * Anno di inizio del programma
	 * @return anno
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Anno di inizio del programma")
	public Long getAnno() {
		return anno;
	}

	public void setAnno(Long anno) {
		this.anno = anno;
	}

	public PubblicaProgrammaLavoriEntry descrizione(String descrizione) {
		this.descrizione = descrizione;
		return this;
	}

	/**
	 * Descrizione del Programma
	 * @return descrizione
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Descrizione del Programma")
	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public PubblicaProgrammaLavoriEntry numeroApprovazione(String numeroApprovazione) {
		this.numeroApprovazione = numeroApprovazione;
		return this;
	}

	/**
	 * Numero approvazione
	 * @return numeroApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Numero approvazione")
	public String getNumeroApprovazione() {
		return numeroApprovazione;
	}

	public void setNumeroApprovazione(String numeroApprovazione) {
		this.numeroApprovazione = numeroApprovazione;
	}

	public PubblicaProgrammaLavoriEntry dataApprovazione(DateTime dataApprovazione) {
		this.dataApprovazione = dataApprovazione;
		return this;
	}

	/**
	 * Data approvazione
	 * @return dataApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Data approvazione")
	public DateTime getDataApprovazione() {
		return dataApprovazione;
	}

	public void setDataApprovazione(DateTime dataApprovazione) {
		this.dataApprovazione = dataApprovazione;
	}

	public PubblicaProgrammaLavoriEntry dataPubblicazioneApprovazione(DateTime dataPubblicazioneApprovazione) {
		this.dataPubblicazioneApprovazione = dataPubblicazioneApprovazione;
		return this;
	}

	/**
	 * Data pubblicazione approvazione
	 * @return dataPubblicazioneApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Data pubblicazione approvazione")
	public DateTime getDataPubblicazioneApprovazione() {
		return dataPubblicazioneApprovazione;
	}

	public void setDataPubblicazioneApprovazione(DateTime dataPubblicazioneApprovazione) {
		this.dataPubblicazioneApprovazione = dataPubblicazioneApprovazione;
	}

	public PubblicaProgrammaLavoriEntry titoloAttoApprovazione(String titoloAttoApprovazione) {
		this.titoloAttoApprovazione = titoloAttoApprovazione;
		return this;
	}

	/**
	 * Titolo atto approvazione
	 * @return titoloAttoApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Titolo atto approvazione")
	public String getTitoloAttoApprovazione() {
		return titoloAttoApprovazione;
	}

	public void setTitoloAttoApprovazione(String titoloAttoApprovazione) {
		this.titoloAttoApprovazione = titoloAttoApprovazione;
	}

	public PubblicaProgrammaLavoriEntry urlAttoApprovazione(String urlAttoApprovazione) {
		this.urlAttoApprovazione = urlAttoApprovazione;
		return this;
	}

	/**
	 * Url atto di approvazione
	 * @return urlAttoApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Url atto di approvazione")
	public String getUrlAttoApprovazione() {
		return urlAttoApprovazione;
	}

	public void setUrlAttoApprovazione(String urlAttoApprovazione) {
		this.urlAttoApprovazione = urlAttoApprovazione;
	}

	public PubblicaProgrammaLavoriEntry numeroAdozione(String numeroAdozione) {
		this.numeroAdozione = numeroAdozione;
		return this;
	}

	/**
	 * Numero adozione
	 * @return numeroAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Numero adozione")
	public String getNumeroAdozione() {
		return numeroAdozione;
	}

	public void setNumeroAdozione(String numeroAdozione) {
		this.numeroAdozione = numeroAdozione;
	}

	public PubblicaProgrammaLavoriEntry dataAdozione(DateTime dataAdozione) {
		this.dataAdozione = dataAdozione;
		return this;
	}

	/**
	 * Data adozione
	 * @return dataAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Data adozione")
	public DateTime getDataAdozione() {
		return dataAdozione;
	}

	public void setDataAdozione(DateTime dataAdozione) {
		this.dataAdozione = dataAdozione;
	}

	public PubblicaProgrammaLavoriEntry dataPubblicazioneAdozione(DateTime dataPubblicazioneAdozione) {
		this.dataPubblicazioneAdozione = dataPubblicazioneAdozione;
		return this;
	}

	/**
	 * Data pubblicazione adozione
	 * @return dataPubblicazioneAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Data pubblicazione adozione")
	public DateTime getDataPubblicazioneAdozione() {
		return dataPubblicazioneAdozione;
	}

	public void setDataPubblicazioneAdozione(DateTime dataPubblicazioneAdozione) {
		this.dataPubblicazioneAdozione = dataPubblicazioneAdozione;
	}

	public PubblicaProgrammaLavoriEntry titoloAttoAdozione(String titoloAttoAdozione) {
		this.titoloAttoAdozione = titoloAttoAdozione;
		return this;
	}

	/**
	 * Titolo atto adozione
	 * @return titoloAttoAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Titolo atto adozione")
	public String getTitoloAttoAdozione() {
		return titoloAttoAdozione;
	}

	public void setTitoloAttoAdozione(String titoloAttoAdozione) {
		this.titoloAttoAdozione = titoloAttoAdozione;
	}

	public PubblicaProgrammaLavoriEntry urlAttoAdozione(String urlAttoAdozione) {
		this.urlAttoAdozione = urlAttoAdozione;
		return this;
	}

	/**
	 * Url atto di adozione
	 * @return urlAttoAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Url atto di adozione")
	public String getUrlAttoAdozione() {
		return urlAttoAdozione;
	}

	public void setUrlAttoAdozione(String urlAttoAdozione) {
		this.urlAttoAdozione = urlAttoAdozione;
	}

	public PubblicaProgrammaLavoriEntry primaPubblicazioneSCP(DateTime primaPubblicazioneSCP) {
		this.primaPubblicazioneSCP = primaPubblicazioneSCP;
		return this;
	}

	/**
	 * Data pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioLavori)
	 * @return primaPubblicazioneSCP
	 **/
	@ApiModelProperty(example = "null", value = "Data pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioLavori)")
	public DateTime getPrimaPubblicazioneSCP() {
		return primaPubblicazioneSCP;
	}

	public void setPrimaPubblicazioneSCP(DateTime primaPubblicazioneSCP) {
		this.primaPubblicazioneSCP = primaPubblicazioneSCP;
	}

	public PubblicaProgrammaLavoriEntry ultimaModificaSCP(DateTime ultimaModificaSCP) {
		this.ultimaModificaSCP = ultimaModificaSCP;
		return this;
	}

	/**
	 * Utima modifica pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioLavori)
	 * @return ultimaModificaSCP
	 **/
	@ApiModelProperty(example = "null", value = "Utima modifica pubblicazione programma su sito SCP (valorizzato solo nel metodo /Programmi/DettaglioLavori)")
	public DateTime getUltimaModificaSCP() {
		return ultimaModificaSCP;
	}

	public void setUltimaModificaSCP(DateTime ultimaModificaSCP) {
		this.ultimaModificaSCP = ultimaModificaSCP;
	}

	public PubblicaProgrammaLavoriEntry referente(DatiGeneraliTecnicoEntry referente) {
		this.referente = referente;
		return this;
	}

	/**
	 * Referente del programma
	 * @return referente
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Referente del programma")
	public DatiGeneraliTecnicoEntry getReferente() {
		return referente;
	}

	public void setReferente(DatiGeneraliTecnicoEntry referente) {
		this.referente = referente;
	}

	public PubblicaProgrammaLavoriEntry opereIncompiute(List<OperaIncompiutaEntry> opereIncompiute) {
		this.opereIncompiute = opereIncompiute;
		return this;
	}

	public PubblicaProgrammaLavoriEntry addOpereIncompiuteItem(OperaIncompiutaEntry opereIncompiuteItem) {
		this.opereIncompiute.add(opereIncompiuteItem);
		return this;
	}

	/**
	 * Lista opere incompiute
	 * @return opereIncompiute
	 **/
	@ApiModelProperty(example = "null", value = "Lista opere incompiute")
	public List<OperaIncompiutaEntry> getOpereIncompiute() {
		return opereIncompiute;
	}

	public void setOpereIncompiute(List<OperaIncompiutaEntry> opereIncompiute) {
		this.opereIncompiute = opereIncompiute;
	}

	public PubblicaProgrammaLavoriEntry interventi(List<InterventoEntry> interventi) {
		this.interventi = interventi;
		return this;
	}

	public PubblicaProgrammaLavoriEntry addInterventiItem(InterventoEntry interventiItem) {
		this.interventi.add(interventiItem);
		return this;
	}

	/**
	 * Lista interventi
	 * @return interventi
	 **/
	@ApiModelProperty(example = "null", value = "Lista interventi")
	public List<InterventoEntry> getInterventi() {
		return interventi;
	}

	public void setInterventi(List<InterventoEntry> interventi) {
		this.interventi = interventi;
	}

	public PubblicaProgrammaLavoriEntry interventiNonRiproposti(List<InterventoNonRipropostoEntry> interventiNonRiproposti) {
		this.interventiNonRiproposti = interventiNonRiproposti;
		return this;
	}

	public PubblicaProgrammaLavoriEntry addInterventiNonRipropostiItem(InterventoNonRipropostoEntry interventiNonRipropostiItem) {
		this.interventiNonRiproposti.add(interventiNonRipropostiItem);
		return this;
	}

	/**
	 * Lista interventi non riproposti
	 * @return interventiNonRiproposti
	 **/
	@ApiModelProperty(example = "null", value = "Lista interventi non riproposti")
	public List<InterventoNonRipropostoEntry> getInterventiNonRiproposti() {
		return interventiNonRiproposti;
	}

	public void setInterventiNonRiproposti(List<InterventoNonRipropostoEntry> interventiNonRiproposti) {
		this.interventiNonRiproposti = interventiNonRiproposti;
	}

	public PubblicaProgrammaLavoriEntry idRicevuto(Long idRicevuto) {
		this.idRicevuto = idRicevuto;
		return this;
	}

	/**
	 * Id univoco generato dal sistema remoto; deve essere utilizzato per le chiamate successive
	 * @return idRicevuto
	 **/
	@ApiModelProperty(example = "null", value = "Id univoco generato dal sistema remoto; deve essere utilizzato per le chiamate successive")
	public Long getIdRicevuto() {
		return idRicevuto;
	}

	public void setIdRicevuto(Long idRicevuto) {
		this.idRicevuto = idRicevuto;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		final PubblicaProgrammaLavoriEntry pubblicaProgrammaLavoriEntry = (PubblicaProgrammaLavoriEntry) o;
		return Objects.equals(this.id, pubblicaProgrammaLavoriEntry.id) &&
				Objects.equals(this.codiceFiscaleSA, pubblicaProgrammaLavoriEntry.codiceFiscaleSA) &&
				Objects.equals(this.ufficio, pubblicaProgrammaLavoriEntry.ufficio) &&
				Objects.equals(this.anno, pubblicaProgrammaLavoriEntry.anno) &&
				Objects.equals(this.descrizione, pubblicaProgrammaLavoriEntry.descrizione) &&
				Objects.equals(this.numeroApprovazione, pubblicaProgrammaLavoriEntry.numeroApprovazione) &&
				Objects.equals(this.dataApprovazione, pubblicaProgrammaLavoriEntry.dataApprovazione) &&
				Objects.equals(this.dataPubblicazioneApprovazione, pubblicaProgrammaLavoriEntry.dataPubblicazioneApprovazione) &&
				Objects.equals(this.titoloAttoApprovazione, pubblicaProgrammaLavoriEntry.titoloAttoApprovazione) &&
				Objects.equals(this.urlAttoApprovazione, pubblicaProgrammaLavoriEntry.urlAttoApprovazione) &&
				Objects.equals(this.numeroAdozione, pubblicaProgrammaLavoriEntry.numeroAdozione) &&
				Objects.equals(this.dataAdozione, pubblicaProgrammaLavoriEntry.dataAdozione) &&
				Objects.equals(this.dataPubblicazioneAdozione, pubblicaProgrammaLavoriEntry.dataPubblicazioneAdozione) &&
				Objects.equals(this.titoloAttoAdozione, pubblicaProgrammaLavoriEntry.titoloAttoAdozione) &&
				Objects.equals(this.urlAttoAdozione, pubblicaProgrammaLavoriEntry.urlAttoAdozione) &&
				Objects.equals(this.primaPubblicazioneSCP, pubblicaProgrammaLavoriEntry.primaPubblicazioneSCP) &&
				Objects.equals(this.ultimaModificaSCP, pubblicaProgrammaLavoriEntry.ultimaModificaSCP) &&
				Objects.equals(this.referente, pubblicaProgrammaLavoriEntry.referente) &&
				Objects.equals(this.opereIncompiute, pubblicaProgrammaLavoriEntry.opereIncompiute) &&
				Objects.equals(this.interventi, pubblicaProgrammaLavoriEntry.interventi) &&
				Objects.equals(this.interventiNonRiproposti, pubblicaProgrammaLavoriEntry.interventiNonRiproposti) &&
				Objects.equals(this.idRicevuto, pubblicaProgrammaLavoriEntry.idRicevuto);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, codiceFiscaleSA, ufficio, anno, descrizione, numeroApprovazione, dataApprovazione, dataPubblicazioneApprovazione, titoloAttoApprovazione, urlAttoApprovazione, numeroAdozione, dataAdozione, dataPubblicazioneAdozione, titoloAttoAdozione, urlAttoAdozione, primaPubblicazioneSCP, ultimaModificaSCP, referente, opereIncompiute, interventi, interventiNonRiproposti, idRicevuto);
	}

	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder();
		sb.append("class PubblicaProgrammaLavoriEntry {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    codiceFiscaleSA: ").append(toIndentedString(codiceFiscaleSA)).append("\n");
		sb.append("    ufficio: ").append(toIndentedString(ufficio)).append("\n");
		sb.append("    anno: ").append(toIndentedString(anno)).append("\n");
		sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
		sb.append("    numeroApprovazione: ").append(toIndentedString(numeroApprovazione)).append("\n");
		sb.append("    dataApprovazione: ").append(toIndentedString(dataApprovazione)).append("\n");
		sb.append("    dataPubblicazioneApprovazione: ").append(toIndentedString(dataPubblicazioneApprovazione)).append("\n");
		sb.append("    titoloAttoApprovazione: ").append(toIndentedString(titoloAttoApprovazione)).append("\n");
		sb.append("    urlAttoApprovazione: ").append(toIndentedString(urlAttoApprovazione)).append("\n");
		sb.append("    numeroAdozione: ").append(toIndentedString(numeroAdozione)).append("\n");
		sb.append("    dataAdozione: ").append(toIndentedString(dataAdozione)).append("\n");
		sb.append("    dataPubblicazioneAdozione: ").append(toIndentedString(dataPubblicazioneAdozione)).append("\n");
		sb.append("    titoloAttoAdozione: ").append(toIndentedString(titoloAttoAdozione)).append("\n");
		sb.append("    urlAttoAdozione: ").append(toIndentedString(urlAttoAdozione)).append("\n");
		sb.append("    primaPubblicazioneSCP: ").append(toIndentedString(primaPubblicazioneSCP)).append("\n");
		sb.append("    ultimaModificaSCP: ").append(toIndentedString(ultimaModificaSCP)).append("\n");
		sb.append("    referente: ").append(toIndentedString(referente)).append("\n");
		sb.append("    opereIncompiute: ").append(toIndentedString(opereIncompiute)).append("\n");
		sb.append("    interventi: ").append(toIndentedString(interventi)).append("\n");
		sb.append("    interventiNonRiproposti: ").append(toIndentedString(interventiNonRiproposti)).append("\n");
		sb.append("    idRicevuto: ").append(toIndentedString(idRicevuto)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}

