/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EJB submodule
 * %%
 * Copyright (C) 2019 - 2025 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/**
 * WSProgrammi
 * Servizio di pubblicazione programmazione lavori, beni e servizi
 *
 * OpenAPI spec version: 2.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package it.csi.cpass.cpassbe.mit.client.model.programmi;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.joda.time.DateTime;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contenitore per i dati di pubblicazione di un programma DM 11/2011
 */
@ApiModel(description = "Contenitore per i dati di pubblicazione di un programma DM 11/2011")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-26T12:24:42.165+01:00")
public class PubblicaProgrammaDM112011Entry   {
	@SerializedName("id")
	private String id = null;

	@SerializedName("codiceFiscaleSA")
	private String codiceFiscaleSA = null;

	@SerializedName("ufficio")
	private String ufficio = null;

	@SerializedName("anno")
	private Long anno = null;

	@SerializedName("descrizione")
	private String descrizione = null;

	@SerializedName("numeroApprovazione")
	private String numeroApprovazione = null;

	@SerializedName("dataApprovazione")
	private DateTime dataApprovazione = null;

	@SerializedName("dataPubblicazioneApprovazione")
	private DateTime dataPubblicazioneApprovazione = null;

	@SerializedName("titoloAttoApprovazione")
	private String titoloAttoApprovazione = null;

	@SerializedName("urlAttoApprovazione")
	private String urlAttoApprovazione = null;

	@SerializedName("numeroAdozione")
	private String numeroAdozione = null;

	@SerializedName("dataAdozione")
	private DateTime dataAdozione = null;

	@SerializedName("dataPubblicazioneAdozione")
	private DateTime dataPubblicazioneAdozione = null;

	@SerializedName("titoloAttoAdozione")
	private String titoloAttoAdozione = null;

	@SerializedName("urlAttoAdozione")
	private String urlAttoAdozione = null;

	@SerializedName("note1")
	private String note1 = null;

	@SerializedName("note2")
	private String note2 = null;

	@SerializedName("note2b")
	private String note2b = null;

	@SerializedName("note3")
	private String note3 = null;

	@SerializedName("note4")
	private String note4 = null;

	@SerializedName("accantonamento")
	private Double accantonamento = null;

	@SerializedName("referente")
	private DatiGeneraliTecnicoEntry referente = null;

	@SerializedName("interventi")
	private List<InterventoDM112011Entry> interventi = new ArrayList<>();

	@SerializedName("fornitureEServizi")
	private List<FornitureServiziDM112011Entry> fornitureEServizi = new ArrayList<>();

	@SerializedName("lavoriEconomia")
	private List<LavoroEconomiaEntry> lavoriEconomia = new ArrayList<>();

	@SerializedName("idRicevuto")
	private Long idRicevuto = null;

	public PubblicaProgrammaDM112011Entry id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * ID del programma
	 * @return id
	 **/
	@ApiModelProperty(example = "null", required = true, value = "ID del programma")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PubblicaProgrammaDM112011Entry codiceFiscaleSA(String codiceFiscaleSA) {
		this.codiceFiscaleSA = codiceFiscaleSA;
		return this;
	}

	/**
	 * Codice Fiscale Stazione appaltante
	 * @return codiceFiscaleSA
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Codice Fiscale Stazione appaltante")
	public String getCodiceFiscaleSA() {
		return codiceFiscaleSA;
	}

	public void setCodiceFiscaleSA(String codiceFiscaleSA) {
		this.codiceFiscaleSA = codiceFiscaleSA;
	}

	public PubblicaProgrammaDM112011Entry ufficio(String ufficio) {
		this.ufficio = ufficio;
		return this;
	}

	/**
	 * Ufficio/area di pertinenza
	 * @return ufficio
	 **/
	@ApiModelProperty(example = "null", value = "Ufficio/area di pertinenza")
	public String getUfficio() {
		return ufficio;
	}

	public void setUfficio(String ufficio) {
		this.ufficio = ufficio;
	}

	public PubblicaProgrammaDM112011Entry anno(Long anno) {
		this.anno = anno;
		return this;
	}

	/**
	 * Anno di inizio del programma
	 * @return anno
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Anno di inizio del programma")
	public Long getAnno() {
		return anno;
	}

	public void setAnno(Long anno) {
		this.anno = anno;
	}

	public PubblicaProgrammaDM112011Entry descrizione(String descrizione) {
		this.descrizione = descrizione;
		return this;
	}

	/**
	 * Descrizione del Programma
	 * @return descrizione
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Descrizione del Programma")
	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public PubblicaProgrammaDM112011Entry numeroApprovazione(String numeroApprovazione) {
		this.numeroApprovazione = numeroApprovazione;
		return this;
	}

	/**
	 * Numero approvazione
	 * @return numeroApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Numero approvazione")
	public String getNumeroApprovazione() {
		return numeroApprovazione;
	}

	public void setNumeroApprovazione(String numeroApprovazione) {
		this.numeroApprovazione = numeroApprovazione;
	}

	public PubblicaProgrammaDM112011Entry dataApprovazione(DateTime dataApprovazione) {
		this.dataApprovazione = dataApprovazione;
		return this;
	}

	/**
	 * Data approvazione
	 * @return dataApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Data approvazione")
	public DateTime getDataApprovazione() {
		return dataApprovazione;
	}

	public void setDataApprovazione(DateTime dataApprovazione) {
		this.dataApprovazione = dataApprovazione;
	}

	public PubblicaProgrammaDM112011Entry dataPubblicazioneApprovazione(DateTime dataPubblicazioneApprovazione) {
		this.dataPubblicazioneApprovazione = dataPubblicazioneApprovazione;
		return this;
	}

	/**
	 * Data pubblicazione approvazione
	 * @return dataPubblicazioneApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Data pubblicazione approvazione")
	public DateTime getDataPubblicazioneApprovazione() {
		return dataPubblicazioneApprovazione;
	}

	public void setDataPubblicazioneApprovazione(DateTime dataPubblicazioneApprovazione) {
		this.dataPubblicazioneApprovazione = dataPubblicazioneApprovazione;
	}

	public PubblicaProgrammaDM112011Entry titoloAttoApprovazione(String titoloAttoApprovazione) {
		this.titoloAttoApprovazione = titoloAttoApprovazione;
		return this;
	}

	/**
	 * Titolo atto approvazione
	 * @return titoloAttoApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Titolo atto approvazione")
	public String getTitoloAttoApprovazione() {
		return titoloAttoApprovazione;
	}

	public void setTitoloAttoApprovazione(String titoloAttoApprovazione) {
		this.titoloAttoApprovazione = titoloAttoApprovazione;
	}

	public PubblicaProgrammaDM112011Entry urlAttoApprovazione(String urlAttoApprovazione) {
		this.urlAttoApprovazione = urlAttoApprovazione;
		return this;
	}

	/**
	 * Url atto di approvazione
	 * @return urlAttoApprovazione
	 **/
	@ApiModelProperty(example = "null", value = "Url atto di approvazione")
	public String getUrlAttoApprovazione() {
		return urlAttoApprovazione;
	}

	public void setUrlAttoApprovazione(String urlAttoApprovazione) {
		this.urlAttoApprovazione = urlAttoApprovazione;
	}

	public PubblicaProgrammaDM112011Entry numeroAdozione(String numeroAdozione) {
		this.numeroAdozione = numeroAdozione;
		return this;
	}

	/**
	 * Numero adozione
	 * @return numeroAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Numero adozione")
	public String getNumeroAdozione() {
		return numeroAdozione;
	}

	public void setNumeroAdozione(String numeroAdozione) {
		this.numeroAdozione = numeroAdozione;
	}

	public PubblicaProgrammaDM112011Entry dataAdozione(DateTime dataAdozione) {
		this.dataAdozione = dataAdozione;
		return this;
	}

	/**
	 * Data adozione
	 * @return dataAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Data adozione")
	public DateTime getDataAdozione() {
		return dataAdozione;
	}

	public void setDataAdozione(DateTime dataAdozione) {
		this.dataAdozione = dataAdozione;
	}

	public PubblicaProgrammaDM112011Entry dataPubblicazioneAdozione(DateTime dataPubblicazioneAdozione) {
		this.dataPubblicazioneAdozione = dataPubblicazioneAdozione;
		return this;
	}

	/**
	 * Data pubblicazione adozione
	 * @return dataPubblicazioneAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Data pubblicazione adozione")
	public DateTime getDataPubblicazioneAdozione() {
		return dataPubblicazioneAdozione;
	}

	public void setDataPubblicazioneAdozione(DateTime dataPubblicazioneAdozione) {
		this.dataPubblicazioneAdozione = dataPubblicazioneAdozione;
	}

	public PubblicaProgrammaDM112011Entry titoloAttoAdozione(String titoloAttoAdozione) {
		this.titoloAttoAdozione = titoloAttoAdozione;
		return this;
	}

	/**
	 * Titolo atto adozione
	 * @return titoloAttoAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Titolo atto adozione")
	public String getTitoloAttoAdozione() {
		return titoloAttoAdozione;
	}

	public void setTitoloAttoAdozione(String titoloAttoAdozione) {
		this.titoloAttoAdozione = titoloAttoAdozione;
	}

	public PubblicaProgrammaDM112011Entry urlAttoAdozione(String urlAttoAdozione) {
		this.urlAttoAdozione = urlAttoAdozione;
		return this;
	}

	/**
	 * Url atto di adozione
	 * @return urlAttoAdozione
	 **/
	@ApiModelProperty(example = "null", value = "Url atto di adozione")
	public String getUrlAttoAdozione() {
		return urlAttoAdozione;
	}

	public void setUrlAttoAdozione(String urlAttoAdozione) {
		this.urlAttoAdozione = urlAttoAdozione;
	}

	public PubblicaProgrammaDM112011Entry note1(String note1) {
		this.note1 = note1;
		return this;
	}

	/**
	 * Note programma triennale
	 * @return note1
	 **/
	@ApiModelProperty(example = "null", value = "Note programma triennale")
	public String getNote1() {
		return note1;
	}

	public void setNote1(String note1) {
		this.note1 = note1;
	}

	public PubblicaProgrammaDM112011Entry note2(String note2) {
		this.note2 = note2;
		return this;
	}

	/**
	 * Note scheda 2
	 * @return note2
	 **/
	@ApiModelProperty(example = "null", value = "Note scheda 2")
	public String getNote2() {
		return note2;
	}

	public void setNote2(String note2) {
		this.note2 = note2;
	}

	public PubblicaProgrammaDM112011Entry note2b(String note2b) {
		this.note2b = note2b;
		return this;
	}

	/**
	 * Note Scheda 2/B
	 * @return note2b
	 **/
	@ApiModelProperty(example = "null", value = "Note Scheda 2/B")
	public String getNote2b() {
		return note2b;
	}

	public void setNote2b(String note2b) {
		this.note2b = note2b;
	}

	public PubblicaProgrammaDM112011Entry note3(String note3) {
		this.note3 = note3;
		return this;
	}

	/**
	 * Note scheda 3 Elenco annuale
	 * @return note3
	 **/
	@ApiModelProperty(example = "null", value = "Note scheda 3 Elenco annuale")
	public String getNote3() {
		return note3;
	}

	public void setNote3(String note3) {
		this.note3 = note3;
	}

	public PubblicaProgrammaDM112011Entry note4(String note4) {
		this.note4 = note4;
		return this;
	}

	/**
	 * Note scheda 4
	 * @return note4
	 **/
	@ApiModelProperty(example = "null", value = "Note scheda 4")
	public String getNote4() {
		return note4;
	}

	public void setNote4(String note4) {
		this.note4 = note4;
	}

	public PubblicaProgrammaDM112011Entry accantonamento(Double accantonamento) {
		this.accantonamento = accantonamento;
		return this;
	}

	/**
	 * Accantonamento primo anno (art. 12 c. 1 dpr 207/2010)
	 * @return accantonamento
	 **/
	@ApiModelProperty(example = "null", value = "Accantonamento primo anno (art. 12 c. 1 dpr 207/2010)")
	public Double getAccantonamento() {
		return accantonamento;
	}

	public void setAccantonamento(Double accantonamento) {
		this.accantonamento = accantonamento;
	}

	public PubblicaProgrammaDM112011Entry referente(DatiGeneraliTecnicoEntry referente) {
		this.referente = referente;
		return this;
	}

	/**
	 * Referente del programma
	 * @return referente
	 **/
	@ApiModelProperty(example = "null", required = true, value = "Referente del programma")
	public DatiGeneraliTecnicoEntry getReferente() {
		return referente;
	}

	public void setReferente(DatiGeneraliTecnicoEntry referente) {
		this.referente = referente;
	}

	public PubblicaProgrammaDM112011Entry interventi(List<InterventoDM112011Entry> interventi) {
		this.interventi = interventi;
		return this;
	}

	public PubblicaProgrammaDM112011Entry addInterventiItem(InterventoDM112011Entry interventiItem) {
		this.interventi.add(interventiItem);
		return this;
	}

	/**
	 * Lista interventi lavori
	 * @return interventi
	 **/
	@ApiModelProperty(example = "null", value = "Lista interventi lavori")
	public List<InterventoDM112011Entry> getInterventi() {
		return interventi;
	}

	public void setInterventi(List<InterventoDM112011Entry> interventi) {
		this.interventi = interventi;
	}

	public PubblicaProgrammaDM112011Entry fornitureEServizi(List<FornitureServiziDM112011Entry> fornitureEServizi) {
		this.fornitureEServizi = fornitureEServizi;
		return this;
	}

	public PubblicaProgrammaDM112011Entry addFornitureEServiziItem(FornitureServiziDM112011Entry fornitureEServiziItem) {
		this.fornitureEServizi.add(fornitureEServiziItem);
		return this;
	}

	/**
	 * Lista interventi forniture e servizi
	 * @return fornitureEServizi
	 **/
	@ApiModelProperty(example = "null", value = "Lista interventi forniture e servizi")
	public List<FornitureServiziDM112011Entry> getFornitureEServizi() {
		return fornitureEServizi;
	}

	public void setFornitureEServizi(List<FornitureServiziDM112011Entry> fornitureEServizi) {
		this.fornitureEServizi = fornitureEServizi;
	}

	public PubblicaProgrammaDM112011Entry lavoriEconomia(List<LavoroEconomiaEntry> lavoriEconomia) {
		this.lavoriEconomia = lavoriEconomia;
		return this;
	}

	public PubblicaProgrammaDM112011Entry addLavoriEconomiaItem(LavoroEconomiaEntry lavoriEconomiaItem) {
		this.lavoriEconomia.add(lavoriEconomiaItem);
		return this;
	}

	/**
	 * Elenco lavori in economia
	 * @return lavoriEconomia
	 **/
	@ApiModelProperty(example = "null", value = "Elenco lavori in economia")
	public List<LavoroEconomiaEntry> getLavoriEconomia() {
		return lavoriEconomia;
	}

	public void setLavoriEconomia(List<LavoroEconomiaEntry> lavoriEconomia) {
		this.lavoriEconomia = lavoriEconomia;
	}

	public PubblicaProgrammaDM112011Entry idRicevuto(Long idRicevuto) {
		this.idRicevuto = idRicevuto;
		return this;
	}

	/**
	 * Id univoco generato dal sistema remoto; deve essere utilizzato per le chiamate successive
	 * @return idRicevuto
	 **/
	@ApiModelProperty(example = "null", value = "Id univoco generato dal sistema remoto; deve essere utilizzato per le chiamate successive")
	public Long getIdRicevuto() {
		return idRicevuto;
	}

	public void setIdRicevuto(Long idRicevuto) {
		this.idRicevuto = idRicevuto;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		final PubblicaProgrammaDM112011Entry pubblicaProgrammaDM112011Entry = (PubblicaProgrammaDM112011Entry) o;
		return Objects.equals(this.id, pubblicaProgrammaDM112011Entry.id) &&
				Objects.equals(this.codiceFiscaleSA, pubblicaProgrammaDM112011Entry.codiceFiscaleSA) &&
				Objects.equals(this.ufficio, pubblicaProgrammaDM112011Entry.ufficio) &&
				Objects.equals(this.anno, pubblicaProgrammaDM112011Entry.anno) &&
				Objects.equals(this.descrizione, pubblicaProgrammaDM112011Entry.descrizione) &&
				Objects.equals(this.numeroApprovazione, pubblicaProgrammaDM112011Entry.numeroApprovazione) &&
				Objects.equals(this.dataApprovazione, pubblicaProgrammaDM112011Entry.dataApprovazione) &&
				Objects.equals(this.dataPubblicazioneApprovazione, pubblicaProgrammaDM112011Entry.dataPubblicazioneApprovazione) &&
				Objects.equals(this.titoloAttoApprovazione, pubblicaProgrammaDM112011Entry.titoloAttoApprovazione) &&
				Objects.equals(this.urlAttoApprovazione, pubblicaProgrammaDM112011Entry.urlAttoApprovazione) &&
				Objects.equals(this.numeroAdozione, pubblicaProgrammaDM112011Entry.numeroAdozione) &&
				Objects.equals(this.dataAdozione, pubblicaProgrammaDM112011Entry.dataAdozione) &&
				Objects.equals(this.dataPubblicazioneAdozione, pubblicaProgrammaDM112011Entry.dataPubblicazioneAdozione) &&
				Objects.equals(this.titoloAttoAdozione, pubblicaProgrammaDM112011Entry.titoloAttoAdozione) &&
				Objects.equals(this.urlAttoAdozione, pubblicaProgrammaDM112011Entry.urlAttoAdozione) &&
				Objects.equals(this.note1, pubblicaProgrammaDM112011Entry.note1) &&
				Objects.equals(this.note2, pubblicaProgrammaDM112011Entry.note2) &&
				Objects.equals(this.note2b, pubblicaProgrammaDM112011Entry.note2b) &&
				Objects.equals(this.note3, pubblicaProgrammaDM112011Entry.note3) &&
				Objects.equals(this.note4, pubblicaProgrammaDM112011Entry.note4) &&
				Objects.equals(this.accantonamento, pubblicaProgrammaDM112011Entry.accantonamento) &&
				Objects.equals(this.referente, pubblicaProgrammaDM112011Entry.referente) &&
				Objects.equals(this.interventi, pubblicaProgrammaDM112011Entry.interventi) &&
				Objects.equals(this.fornitureEServizi, pubblicaProgrammaDM112011Entry.fornitureEServizi) &&
				Objects.equals(this.lavoriEconomia, pubblicaProgrammaDM112011Entry.lavoriEconomia) &&
				Objects.equals(this.idRicevuto, pubblicaProgrammaDM112011Entry.idRicevuto);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, codiceFiscaleSA, ufficio, anno, descrizione, numeroApprovazione, dataApprovazione, dataPubblicazioneApprovazione, titoloAttoApprovazione, urlAttoApprovazione, numeroAdozione, dataAdozione, dataPubblicazioneAdozione, titoloAttoAdozione, urlAttoAdozione, note1, note2, note2b, note3, note4, accantonamento, referente, interventi, fornitureEServizi, lavoriEconomia, idRicevuto);
	}

	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder();
		sb.append("class PubblicaProgrammaDM112011Entry {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    codiceFiscaleSA: ").append(toIndentedString(codiceFiscaleSA)).append("\n");
		sb.append("    ufficio: ").append(toIndentedString(ufficio)).append("\n");
		sb.append("    anno: ").append(toIndentedString(anno)).append("\n");
		sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
		sb.append("    numeroApprovazione: ").append(toIndentedString(numeroApprovazione)).append("\n");
		sb.append("    dataApprovazione: ").append(toIndentedString(dataApprovazione)).append("\n");
		sb.append("    dataPubblicazioneApprovazione: ").append(toIndentedString(dataPubblicazioneApprovazione)).append("\n");
		sb.append("    titoloAttoApprovazione: ").append(toIndentedString(titoloAttoApprovazione)).append("\n");
		sb.append("    urlAttoApprovazione: ").append(toIndentedString(urlAttoApprovazione)).append("\n");
		sb.append("    numeroAdozione: ").append(toIndentedString(numeroAdozione)).append("\n");
		sb.append("    dataAdozione: ").append(toIndentedString(dataAdozione)).append("\n");
		sb.append("    dataPubblicazioneAdozione: ").append(toIndentedString(dataPubblicazioneAdozione)).append("\n");
		sb.append("    titoloAttoAdozione: ").append(toIndentedString(titoloAttoAdozione)).append("\n");
		sb.append("    urlAttoAdozione: ").append(toIndentedString(urlAttoAdozione)).append("\n");
		sb.append("    note1: ").append(toIndentedString(note1)).append("\n");
		sb.append("    note2: ").append(toIndentedString(note2)).append("\n");
		sb.append("    note2b: ").append(toIndentedString(note2b)).append("\n");
		sb.append("    note3: ").append(toIndentedString(note3)).append("\n");
		sb.append("    note4: ").append(toIndentedString(note4)).append("\n");
		sb.append("    accantonamento: ").append(toIndentedString(accantonamento)).append("\n");
		sb.append("    referente: ").append(toIndentedString(referente)).append("\n");
		sb.append("    interventi: ").append(toIndentedString(interventi)).append("\n");
		sb.append("    fornitureEServizi: ").append(toIndentedString(fornitureEServizi)).append("\n");
		sb.append("    lavoriEconomia: ").append(toIndentedString(lavoriEconomia)).append("\n");
		sb.append("    idRicevuto: ").append(toIndentedString(idRicevuto)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}

