/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - SICRAWEB
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package fdewsappjricercagateway;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FdeWSAppjRicercaGatewayService", targetNamespace = "urn:FdeWSAppjRicercaGateway", wsdlLocation = "/wsdl/FdeWSAppjRicercaGateway.wsdl")
public class FdeWSAppjRicercaGatewayService
    extends Service
{

    private final static URL FDEWSAPPJRICERCAGATEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException FDEWSAPPJRICERCAGATEWAYSERVICE_EXCEPTION;
    private final static QName FDEWSAPPJRICERCAGATEWAYSERVICE_QNAME = new QName("urn:FdeWSAppjRicercaGateway", "FdeWSAppjRicercaGatewayService");

    static {
        FDEWSAPPJRICERCAGATEWAYSERVICE_WSDL_LOCATION = fdewsappjricercagateway.FdeWSAppjRicercaGatewayService.class.getResource("/wsdl/FdeWSAppjRicercaGateway.wsdl");
        WebServiceException e = null;
        if (FDEWSAPPJRICERCAGATEWAYSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/FdeWSAppjRicercaGateway.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FDEWSAPPJRICERCAGATEWAYSERVICE_EXCEPTION = e;
    }

    public FdeWSAppjRicercaGatewayService() {
        super(__getWsdlLocation(), FDEWSAPPJRICERCAGATEWAYSERVICE_QNAME);
    }

    public FdeWSAppjRicercaGatewayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FDEWSAPPJRICERCAGATEWAYSERVICE_QNAME, features);
    }

    public FdeWSAppjRicercaGatewayService(URL wsdlLocation) {
        super(wsdlLocation, FDEWSAPPJRICERCAGATEWAYSERVICE_QNAME);
    }

    public FdeWSAppjRicercaGatewayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FDEWSAPPJRICERCAGATEWAYSERVICE_QNAME, features);
    }

    public FdeWSAppjRicercaGatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FdeWSAppjRicercaGatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FdeWSAppjRicercaGateway
     */
    @WebEndpoint(name = "FdeWSAppjRicercaGateway")
    public FdeWSAppjRicercaGateway getFdeWSAppjRicercaGateway() {
        return super.getPort(new QName("urn:FdeWSAppjRicercaGateway", "FdeWSAppjRicercaGateway"), FdeWSAppjRicercaGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns FdeWSAppjRicercaGateway
     */
    @WebEndpoint(name = "FdeWSAppjRicercaGateway")
    public FdeWSAppjRicercaGateway getFdeWSAppjRicercaGateway(WebServiceFeature... features) {
        return super.getPort(new QName("urn:FdeWSAppjRicercaGateway", "FdeWSAppjRicercaGateway"), FdeWSAppjRicercaGateway.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FDEWSAPPJRICERCAGATEWAYSERVICE_EXCEPTION!= null) {
            throw FDEWSAPPJRICERCAGATEWAYSERVICE_EXCEPTION;
        }
        return FDEWSAPPJRICERCAGATEWAYSERVICE_WSDL_LOCATION;
    }

}
