
package com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_consiglio_reg;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CUSCSI_SOA_CONSIGLIO_REG_Service", targetNamespace = "http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_consiglio_reg/", wsdlLocation = "/wsdl/werwre/cuscsi_soa_consiglio_reg.wsdl")
public class CUSCSISOACONSIGLIOREGService
    extends Service
{

    private final static URL CUSCSISOACONSIGLIOREGSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSCSISOACONSIGLIOREGSERVICE_EXCEPTION;
    private final static QName CUSCSISOACONSIGLIOREGSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_consiglio_reg/", "CUSCSI_SOA_CONSIGLIO_REG_Service");

    static {
        CUSCSISOACONSIGLIOREGSERVICE_WSDL_LOCATION = com.oracle.xmlns.apps.per.soaprovider.plsql.cuscsi_soa_consiglio_reg.CUSCSISOACONSIGLIOREGService.class.getResource("/wsdl/werwre/cuscsi_soa_consiglio_reg.wsdl");
        WebServiceException e = null;
        if (CUSCSISOACONSIGLIOREGSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/werwre/cuscsi_soa_consiglio_reg.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CUSCSISOACONSIGLIOREGSERVICE_EXCEPTION = e;
    }

    public CUSCSISOACONSIGLIOREGService() {
        super(__getWsdlLocation(), CUSCSISOACONSIGLIOREGSERVICE_QNAME);
    }

    public CUSCSISOACONSIGLIOREGService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSCSISOACONSIGLIOREGSERVICE_QNAME, features);
    }

    public CUSCSISOACONSIGLIOREGService(URL wsdlLocation) {
        super(wsdlLocation, CUSCSISOACONSIGLIOREGSERVICE_QNAME);
    }

    public CUSCSISOACONSIGLIOREGService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSCSISOACONSIGLIOREGSERVICE_QNAME, features);
    }

    public CUSCSISOACONSIGLIOREGService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUSCSISOACONSIGLIOREGService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CUSCSISOACONSIGLIOREGPortType
     */
    @WebEndpoint(name = "CUSCSI_SOA_CONSIGLIO_REG_Port")
    public CUSCSISOACONSIGLIOREGPortType getCUSCSISOACONSIGLIOREGPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_consiglio_reg/", "CUSCSI_SOA_CONSIGLIO_REG_Port"), CUSCSISOACONSIGLIOREGPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns CUSCSISOACONSIGLIOREGPortType
     */
    @WebEndpoint(name = "CUSCSI_SOA_CONSIGLIO_REG_Port")
    public CUSCSISOACONSIGLIOREGPortType getCUSCSISOACONSIGLIOREGPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/per/soaprovider/plsql/cuscsi_soa_consiglio_reg/", "CUSCSI_SOA_CONSIGLIO_REG_Port"), CUSCSISOACONSIGLIOREGPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSCSISOACONSIGLIOREGSERVICE_EXCEPTION!= null) {
            throw CUSCSISOACONSIGLIOREGSERVICE_EXCEPTION;
        }
        return CUSCSISOACONSIGLIOREGSERVICE_WSDL_LOCATION;
    }

}
