/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - SICRAWEB
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package fdewsappjdocumentigateway;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "fault", targetNamespace = "urn:FdeWSAppjDocumentiGateway")
public class SagaException
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 135411981953643765L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private it.saga.library.messages.SagaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SagaException(String message, it.saga.library.messages.SagaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SagaException(String message, it.saga.library.messages.SagaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.saga.library.messages.SagaException
     */
    public it.saga.library.messages.SagaException getFaultInfo() {
        return faultInfo;
    }

}
