<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RelationshipsService" targetNamespace="relationshipsservice.acaris.acta.doqui.it" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:common="common.acaris.acta.doqui.it" xmlns:tns="relationshipsservice.acaris.acta.doqui.it" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:archive="archive.acaris.acta.doqui.it" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="common.acaris.acta.doqui.it">
			<xsd:include schemaLocation="http://tst-applogic.reteunitaria.piemonte.it/actasrv/relationshipsWS?xsd=ACARIS-Common.xsd"/>
		</xsd:schema>
    <xsd:schema targetNamespace="archive.acaris.acta.doqui.it">
			<xsd:include schemaLocation="http://tst-applogic.reteunitaria.piemonte.it/actasrv/relationshipsWS?xsd=ACARIS-Archive.xsd"/>
			<xsd:include schemaLocation="http://tst-applogic.reteunitaria.piemonte.it/actasrv/relationshipsWS?xsd=ACARIS-ArchiveMessaging.xsd"/>
		</xsd:schema>
  </wsdl:types>
  <wsdl:message name="acarisException">
    <wsdl:part name="fault" element="common:acarisFault">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getObjectRelationshipsResponse">
    <wsdl:part name="output" element="archive:getObjectRelationshipsResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getObjectRelationshipsRequest">
    <wsdl:part name="input" element="archive:getObjectRelationships">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RelationshipsServicePort">
    <wsdl:operation name="getObjectRelationships">
      <wsdl:input message="tns:getObjectRelationshipsRequest">
    </wsdl:input>
      <wsdl:output message="tns:getObjectRelationshipsResponse">
    </wsdl:output>
      <wsdl:fault name="getObjectRelationshipsFault" message="tns:acarisException">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RelationshipsServiceBinding" type="tns:RelationshipsServicePort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getObjectRelationships">
      <soap:operation/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getObjectRelationshipsFault">
        <soap:fault name="getObjectRelationshipsFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RelationshipsService">
    <wsdl:port name="RelationshipsServicePort" binding="tns:RelationshipsServiceBinding">
      <soap:address location="http://tst-api-piemonte.ecosis.csi.it/documentale/acaris-test-relationship/v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
