/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EXPOSED submodule
 * %%
 * Copyright (C) 2019 - 2025 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.csi.cpass.cpassbe.data.verificaevasione;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsImplService", targetNamespace = "http://cpass.csi.it/cpassbe/data/verificaevasione", wsdlLocation = "/wsdl/verifica_evasione.wsdl")
public class WsImplService
    extends Service
{

    private final static URL WSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSIMPLSERVICE_EXCEPTION;
    private final static QName WSIMPLSERVICE_QNAME = new QName("http://cpass.csi.it/cpassbe/data/verificaevasione", "WsImplService");

    static {
        WSIMPLSERVICE_WSDL_LOCATION = it.csi.cpass.cpassbe.data.verificaevasione.WsImplService.class.getResource("/wsdl/verifica_evasione.wsdl");
        WebServiceException e = null;
        if (WSIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/verifica_evasione.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSIMPLSERVICE_EXCEPTION = e;
    }

    public WsImplService() {
        super(__getWsdlLocation(), WSIMPLSERVICE_QNAME);
    }

    public WsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSIMPLSERVICE_QNAME, features);
    }

    public WsImplService(URL wsdlLocation) {
        super(wsdlLocation, WSIMPLSERVICE_QNAME);
    }

    public WsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSIMPLSERVICE_QNAME, features);
    }

    public WsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WsImplPort")
    public WSInterface getWsImplPort() {
        return super.getPort(new QName("http://cpass.csi.it/cpassbe/data/verificaevasione", "WsImplPort"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WsImplPort")
    public WSInterface getWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cpass.csi.it/cpassbe/data/verificaevasione", "WsImplPort"), WSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSIMPLSERVICE_EXCEPTION!= null) {
            throw WSIMPLSERVICE_EXCEPTION;
        }
        return WSIMPLSERVICE_WSDL_LOCATION;
    }

}
