/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EXPOSED submodule
 * %%
 * Copyright (C) 2019 - 2025 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.csi.cpass.cpassbe.data.verificaevasione;

import java.util.stream.Collectors;

import javax.ejb.EJB;
import javax.jws.WebService;
import javax.xml.ws.BindingType;

import it.csi.cpass.cpassbe.ejb.business.be.facade.ExposedFacade;
import it.csi.cpass.cpassbe.ejb.business.be.service.response.exposed.VerificaEvasioneResponse;
import it.csi.cpass.cpassbe.lib.exposed.dto.Evasione;
import it.csi.cpass.cpassbe.lib.mapper.CpassMappers;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "WsImplPort", serviceName = "WsImplService", targetNamespace = "http://cpass.csi.it/cpassbe/data/verificaevasione", /*wsdlLocation = "/wsdl/verifica_evasione.wsdl", */endpointInterface = "it.csi.cpass.cpassbe.data.verificaevasione.WSInterface")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class WsImplService_WsImplPortImpl
    implements WSInterface
{

	@EJB
	private ExposedFacade exposedFacade;

    public WsImplService_WsImplPortImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.cpass.cpassbe.data.verificaevasione.VerificaEvasioneResponse
     */
    public it.csi.cpass.cpassbe.data.verificaevasione.VerificaEvasioneResponse verificaEvasione(VerificaEvasione parameters) {
    	
    	Evasione evasioni = CpassMappers.EVASIONI.toModel(parameters.getEvasioni());
       	VerificaEvasioneResponse  responseJaxrs = exposedFacade.verificaEvasione(evasioni);
		String collect = responseJaxrs.getApiErrors().stream().map(x -> x.getFullErrorMessage(false)).collect(Collectors.joining(", "));
		
        it.csi.cpass.cpassbe.data.verificaevasione.VerificaEvasioneResponse responseJaxws = new it.csi.cpass.cpassbe.data.verificaevasione.VerificaEvasioneResponse();
        EsitoServizio esitoServizio = new EsitoServizio();
        esitoServizio.setEsito(Esito.valueOf(responseJaxrs.getEsito()));
        esitoServizio.getErrori().add(collect);
        
        responseJaxws.setReturn(esitoServizio);
		return responseJaxws;
    }

}
