/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - EXPOSED submodule
 * %%
 * Copyright (C) 2019 - 2025 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.csi.cpass.cpassbe.data.verificaevasione;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSInterface", targetNamespace = "http://cpass.csi.it/cpassbe/data/verificaevasione")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.cpass.cpassbe.data.verificaevasione.VerificaEvasioneResponse
     */
    @WebMethod
    @WebResult(name = "verificaEvasioneResponse", targetNamespace = "http://cpass.csi.it/cpassbe/data/verificaevasione", partName = "parameters")
    public VerificaEvasioneResponse verificaEvasione(
        @WebParam(name = "verificaEvasione", targetNamespace = "http://cpass.csi.it/cpassbe/data/verificaevasione", partName = "parameters")
        VerificaEvasione parameters);

}
