/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.objectservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ObjectService", targetNamespace = "objectservice.acaris.acta.doqui.it", wsdlLocation = "/wsdl/objectWS.wsdl")
public class ObjectService
    extends Service
{

    private final static URL OBJECTSERVICE_WSDL_LOCATION;
    private final static WebServiceException OBJECTSERVICE_EXCEPTION;
    private final static QName OBJECTSERVICE_QNAME = new QName("objectservice.acaris.acta.doqui.it", "ObjectService");

    static {
        OBJECTSERVICE_WSDL_LOCATION = it.doqui.acta.acaris.objectservice.ObjectService.class.getResource("/wsdl/objectWS.wsdl");
        WebServiceException e = null;
        if (OBJECTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/objectWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        OBJECTSERVICE_EXCEPTION = e;
    }

    public ObjectService() {
        super(__getWsdlLocation(), OBJECTSERVICE_QNAME);
    }

    public ObjectService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OBJECTSERVICE_QNAME, features);
    }

    public ObjectService(URL wsdlLocation) {
        super(wsdlLocation, OBJECTSERVICE_QNAME);
    }

    public ObjectService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OBJECTSERVICE_QNAME, features);
    }

    public ObjectService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObjectService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ObjectServicePort
     */
    @WebEndpoint(name = "ObjectServicePort")
    public ObjectServicePort getObjectServicePort() {
        return super.getPort(new QName("objectservice.acaris.acta.doqui.it", "ObjectServicePort"), ObjectServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ObjectServicePort
     */
    @WebEndpoint(name = "ObjectServicePort")
    public ObjectServicePort getObjectServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("objectservice.acaris.acta.doqui.it", "ObjectServicePort"), ObjectServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OBJECTSERVICE_EXCEPTION!= null) {
            throw OBJECTSERVICE_EXCEPTION;
        }
        return OBJECTSERVICE_WSDL_LOCATION;
    }

}
