/*-
 * ========================LICENSE_START=================================
 * CPASS BackEnd - INTEGRATION submodule - ACTA
 * %%
 * Copyright (C) 2019 - 2023 CSI Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2019 - 2023 | CSI Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.doqui.acta.acaris.objectservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.doqui.acta.acaris.archive.AddRenditionStream;
import it.doqui.acta.acaris.archive.AddRenditionStreamResponse;
import it.doqui.acta.acaris.archive.CloseFolder;
import it.doqui.acta.acaris.archive.CloseFolderResponse;
import it.doqui.acta.acaris.archive.CreateAssociativeDocument;
import it.doqui.acta.acaris.archive.CreateAssociativeDocumentResponse;
import it.doqui.acta.acaris.archive.CreateDocument;
import it.doqui.acta.acaris.archive.CreateDocumentResponse;
import it.doqui.acta.acaris.archive.CreateFolder;
import it.doqui.acta.acaris.archive.CreateFolderResponse;
import it.doqui.acta.acaris.archive.CreateRelationship;
import it.doqui.acta.acaris.archive.CreateRelationshipResponse;
import it.doqui.acta.acaris.archive.GetContentStream;
import it.doqui.acta.acaris.archive.GetContentStreamResponse;
import it.doqui.acta.acaris.archive.GetProperties;
import it.doqui.acta.acaris.archive.GetPropertiesResponse;
import it.doqui.acta.acaris.archive.MoveDocument;
import it.doqui.acta.acaris.archive.MoveDocumentResponse;
import it.doqui.acta.acaris.archive.SetContentStream;
import it.doqui.acta.acaris.archive.SetContentStreamResponse;
import it.doqui.acta.acaris.archive.UpdateProperties;
import it.doqui.acta.acaris.archive.UpdatePropertiesResponse;
import it.doqui.acta.acaris.common.GetPropertiesMassive;
import it.doqui.acta.acaris.common.GetPropertiesMassiveResponse;
import it.doqui.acta.acaris.common.Query;
import it.doqui.acta.acaris.common.QueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ObjectServicePort", targetNamespace = "objectservice.acaris.acta.doqui.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.doqui.acta.acaris.archive.ObjectFactory.class,
    it.doqui.acta.acaris.common.ObjectFactory.class
})
public interface ObjectServicePort {


    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.CreateFolderResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "createFolderResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public CreateFolderResponse createFolder(
        @WebParam(name = "createFolder", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        CreateFolder input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.GetPropertiesResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesResponse getProperties(
        @WebParam(name = "getProperties", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        GetProperties input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.GetPropertiesMassiveResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getPropertiesMassiveResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public GetPropertiesMassiveResponse getPropertiesMassive(
        @WebParam(name = "getPropertiesMassive", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        GetPropertiesMassive input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.CreateDocumentResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "createDocumentResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public CreateDocumentResponse createDocument(
        @WebParam(name = "createDocument", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        CreateDocument input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.CreateAssociativeDocumentResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "createAssociativeDocumentResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public CreateAssociativeDocumentResponse createAssociativeDocument(
        @WebParam(name = "createAssociativeDocument", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        CreateAssociativeDocument input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.CreateRelationshipResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "createRelationshipResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public CreateRelationshipResponse createRelationship(
        @WebParam(name = "createRelationship", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        CreateRelationship input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.GetContentStreamResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "getContentStreamResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public GetContentStreamResponse getContentStream(
        @WebParam(name = "getContentStream", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        GetContentStream input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.AddRenditionStreamResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "addRenditionStreamResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public AddRenditionStreamResponse addRenditionStream(
        @WebParam(name = "addRenditionStream", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        AddRenditionStream input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.UpdatePropertiesResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "updatePropertiesResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public UpdatePropertiesResponse updateProperties(
        @WebParam(name = "updateProperties", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        UpdateProperties input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.SetContentStreamResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "setContentStreamResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public SetContentStreamResponse setContentStream(
        @WebParam(name = "setContentStream", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        SetContentStream input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.common.QueryResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "queryResponse", targetNamespace = "common.acaris.acta.doqui.it", partName = "output")
    public QueryResponse query(
        @WebParam(name = "query", targetNamespace = "common.acaris.acta.doqui.it", partName = "input")
        Query input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.MoveDocumentResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "moveDocumentResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public MoveDocumentResponse moveDocument(
        @WebParam(name = "moveDocument", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        MoveDocument input)
        throws AcarisException
    ;

    /**
     * 
     * @param input
     * @return
     *     returns it.doqui.acta.acaris.archive.CloseFolderResponse
     * @throws AcarisException
     */
    @WebMethod
    @WebResult(name = "closeFolderResponse", targetNamespace = "archive.acaris.acta.doqui.it", partName = "output")
    public CloseFolderResponse closeFolder(
        @WebParam(name = "closeFolder", targetNamespace = "archive.acaris.acta.doqui.it", partName = "input")
        CloseFolder input)
        throws AcarisException
    ;

}
